import QtQuick 2.15
import org.kde.kcmutils as KCM

// Plasma injects every main.xml key (+ Default) into each config page root.
KCM.SimpleKCM {
    id: root

    property string cfg_defaultView
    property string cfg_defaultViewDefault
    property bool cfg_showCompleted
    property bool cfg_showCompletedDefault
    property bool cfg_blurBackground
    property bool cfg_blurBackgroundDefault
    property string cfg_enabledCollections
    property string cfg_enabledCollectionsDefault
    property string cfg_hiddenProjects
    property string cfg_hiddenProjectsDefault
    property string cfg_hiddenLabels
    property string cfg_hiddenLabelsDefault
    property string cfg_sidebarRowSize
    property string cfg_sidebarRowSizeDefault
    property string cfg_newTaskProjectMode
    property string cfg_newTaskProjectModeDefault
    property string cfg_newTaskDefaultCollectionId
    property string cfg_newTaskDefaultCollectionIdDefault
    property bool cfg_catchUpEnabled
    property bool cfg_catchUpEnabledDefault
    property int cfg_catchUpDays
    property int cfg_catchUpDaysDefault
    property int cfg_morningHour
    property int cfg_morningHourDefault
    property int cfg_afternoonHour
    property int cfg_afternoonHourDefault
    property int cfg_eveningHour
    property int cfg_eveningHourDefault
    property bool cfg_showJoinButton
    property bool cfg_showJoinButtonDefault
    property bool cfg_rememberLastView
    property bool cfg_rememberLastViewDefault
    property string cfg_lastView
    property string cfg_lastViewDefault
    property string cfg_density
    property string cfg_densityDefault
    property int cfg_sidebarWidthUnits
    property int cfg_sidebarWidthUnitsDefault
    property int cfg_overlayDimStep
    property int cfg_overlayDimStepDefault
    property bool cfg_reducedMotion
    property bool cfg_reducedMotionDefault
    property int cfg_scrollSpeed
    property int cfg_scrollSpeedDefault
    property bool cfg_showEmptyProjects
    property bool cfg_showEmptyProjectsDefault
    property bool cfg_showSidebarCounts
    property bool cfg_showSidebarCountsDefault
    property bool cfg_countsExcludeCollapsed
    property bool cfg_countsExcludeCollapsedDefault
    property bool cfg_showDateChip
    property bool cfg_showDateChipDefault
    property bool cfg_showLabelChips
    property bool cfg_showLabelChipsDefault
    property bool cfg_showPriorityChip
    property bool cfg_showPriorityChipDefault
    property bool cfg_showRecurringIcon
    property bool cfg_showRecurringIconDefault
    property bool cfg_showProgressChip
    property bool cfg_showProgressChipDefault
    property bool cfg_showStatusChip
    property bool cfg_showStatusChipDefault
    property bool cfg_showSecrecyChip
    property bool cfg_showSecrecyChipDefault
    property bool cfg_showLocationChip
    property bool cfg_showLocationChipDefault
    property string cfg_defaultDueMode
    property string cfg_defaultDueModeDefault
    property bool cfg_confirmDelete
    property bool cfg_confirmDeleteDefault
    property string cfg_clickAction
    property string cfg_clickActionDefault
    property string cfg_sortMode
    property string cfg_sortModeDefault
    property string cfg_sortScope
    property string cfg_sortScopeDefault
    property string cfg_sortModeByView
    property string cfg_sortModeByViewDefault
    property string cfg_listGroupMode
    property string cfg_listGroupModeDefault
    property string cfg_panelBadge
    property string cfg_panelBadgeDefault
    property string cfg_panelBadgeStyle
    property string cfg_panelBadgeStyleDefault
    property string cfg_panelBadgeOverdueColor
    property string cfg_panelBadgeOverdueColorDefault
    property string cfg_panelTooltip
    property string cfg_panelTooltipDefault
    property bool cfg_searchTitleOnly
    property bool cfg_searchTitleOnlyDefault
    property bool cfg_completeChildren
    property bool cfg_completeChildrenDefault
    property bool cfg_notificationsEnabled
    property bool cfg_notificationsEnabledDefault
    property int cfg_defaultReminderMinutes
    property int cfg_defaultReminderMinutesDefault
    property string cfg_projectColors
    property string cfg_projectColorsDefault
    property string cfg_labelColors
    property string cfg_labelColorsDefault
    property string cfg_locationColors
    property string cfg_locationColorsDefault
    property string cfg_hiddenLocations
    property string cfg_hiddenLocationsDefault
    property int cfg_descriptionPreviewLines
    property int cfg_descriptionPreviewLinesDefault
    property string cfg_sidebarSectionOrder
    property string cfg_sidebarSectionOrderDefault
    property string cfg_hiddenSidebarSections
    property string cfg_hiddenSidebarSectionsDefault
    property string cfg_sidebarViewOrder
    property string cfg_sidebarViewOrderDefault
    property string cfg_hiddenViews
    property string cfg_hiddenViewsDefault
    property bool cfg_searchCaseSensitive
    property bool cfg_searchCaseSensitiveDefault
    property bool cfg_relativeDates
    property bool cfg_relativeDatesDefault
    property bool cfg_showTimeOnRow
    property bool cfg_showTimeOnRowDefault
    property bool cfg_completeNeedsModifier
    property bool cfg_completeNeedsModifierDefault
    property bool cfg_quietHoursEnabled
    property bool cfg_quietHoursEnabledDefault
    property int cfg_quietHoursStart
    property int cfg_quietHoursStartDefault
    property int cfg_quietHoursEnd
    property int cfg_quietHoursEndDefault
    property bool cfg_suppressRemindersDuringEvents
    property bool cfg_suppressRemindersDuringEventsDefault
    property string cfg_busyCalendarIds
    property string cfg_busyCalendarIdsDefault
    property string cfg_mainPaneMode
    property string cfg_mainPaneModeDefault
    property string cfg_smartViews
    property string cfg_smartViewsDefault
    property string cfg_kanbanColumnSource
    property string cfg_kanbanColumnSourceDefault
    property string cfg_kanbanWriteMode
    property string cfg_kanbanWriteModeDefault
    property string cfg_kanbanManualOrder
    property string cfg_kanbanManualOrderDefault
    property string cfg_kanbanSortModeByViewColumn
    property string cfg_kanbanSortModeByViewColumnDefault
    property string cfg_swimlaneLaneAxis
    property string cfg_swimlaneLaneAxisDefault
    property string cfg_swimlaneTimeBucket
    property string cfg_swimlaneTimeBucketDefault
    property string cfg_planTimeBucket
    property string cfg_planTimeBucketDefault
    property int cfg_planHorizon
    property int cfg_planHorizonDefault
    property bool cfg_planShowUndated
    property bool cfg_planShowUndatedDefault
    property bool cfg_planShowCompleted
    property bool cfg_planShowCompletedDefault
    property bool cfg_multiSelectEnabled
    property bool cfg_multiSelectEnabledDefault
    property bool cfg_verboseJournalLogging
    property bool cfg_verboseJournalLoggingDefault
    property bool cfg_infoJournalLogging
    property bool cfg_infoJournalLoggingDefault
}
