#!/usr/bin/env python3
"""Merge new QML strings into po/extra_translations.py."""
from __future__ import annotations

import re
import sys
from pathlib import Path

PO_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(PO_DIR))

from extra_translations import EXTRA  # noqa: E402
from new_strings import NEW, OVERRIDES  # noqa: E402

QML_I18N = re.compile(r'i18n(?:c\s*\(\s*"[^"]*"\s*,\s*)?\(\s*"((?:[^"\\]|\\.)*)"')


def extract_qml_strings() -> list[str]:
    root = PO_DIR.parent / "plasmoid"
    found: set[str] = set()
    for qml in sorted(root.rglob("*.qml")):
        for match in QML_I18N.finditer(qml.read_text(encoding="utf-8")):
            found.add(match.group(1))
    return sorted(found)


def dict_to_source(name: str, data: dict[str, str]) -> str:
    lines = [f"{name} = {{"]
    for key in sorted(data.keys()):
        val = data[key]
        if "\n" in key or "\n" in val:
            lines.append(f"    {key!r}:")
            lines.append(f"        {val!r},")
        else:
            lines.append(f"    {key!r}: {val!r},")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    qml_strings = extract_qml_strings()
    langs = ["de", "es", "fr", "ja", "zh_CN"]
    catalogs: dict[str, dict[str, str]] = {}

    for lang in langs:
        merged = dict(EXTRA.get(lang, {}))
        merged.update(NEW.get(lang, {}))
        merged.update(OVERRIDES.get(lang, {}))
        catalogs[lang] = {msgid: merged[msgid] for msgid in qml_strings if msgid in merged}

    for lang in langs:
        missing = [s for s in qml_strings if s not in catalogs[lang]]
        if missing:
            print(f"ERROR {lang}: {len(missing)} missing — add to po/new_strings.py", file=sys.stderr)
            for item in missing[:20]:
                print(f"  {item!r}", file=sys.stderr)
            sys.exit(1)

    out = PO_DIR / "extra_translations.py"
    parts = [
        '"""Translations for all supported locales (generated by _merge_catalog.py)."""',
        "",
        dict_to_source("DE", catalogs["de"]),
        "",
        dict_to_source("ES", catalogs["es"]),
        "",
        dict_to_source("FR", catalogs["fr"]),
        "",
        dict_to_source("JA", catalogs["ja"]),
        "",
        dict_to_source("ZH_CN", catalogs["zh_CN"]),
        "",
        'EXTRA = {"de": DE, "es": ES, "fr": FR, "ja": JA, "zh_CN": ZH_CN}',
        "",
    ]
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {out} ({len(qml_strings)} strings × {len(langs)} langs)")


if __name__ == "__main__":
    main()
