"""Translations for strings newly extracted from QML (not yet in the catalog)."""

NEW = {
    "de": {
        "%1 grid units": "%1 Raster-Einheiten",
        "%1:00": "%1:00",
        "1 day before": "1 Tag vorher",
        "1 hour before": "1 Stunde vorher",
        "1 line": "1 Zeile",
        "15 minutes before": "15 Minuten vorher",
        "2 lines": "2 Zeilen",
        "Accent (highlight)": "Akzent (Hervorhebung)",
        "Afternoon": "Nachmittag",
        "Afternoon starts": "Nachmittag beginnt",
        "Akonadi is not running": "Akonadi läuft nicht",
        "All views": "Alle Ansichten",
        "Applies when the badge shows the overdue count.":
            "Gilt, wenn das Badge die Anzahl überfälliger Aufgaben anzeigt.",
        "Applies when the badge shows today and there are overdue tasks.":
            "Gilt, wenn das Badge Heute anzeigt und überfällige Aufgaben vorhanden sind.",
        "Ask before deleting a task": "Vor dem Löschen einer Aufgabe nachfragen",
        "At due time": "Zur Fälligkeit",
        "Background": "Hintergrund",
        "Badge display": "Badge-Anzeige",
        "Blurred wallpaper behind the widget": "Unscharfes Hintergrundbild hinter dem Widget",
        "Calendars for event suppression": "Kalender zur Terminunterdrückung",
        "Case sensitive": "Groß-/Kleinschreibung beachten",
        "Catch-up": "Nachholen",
        "Checkbox": "Kontrollkästchen",
        "Choose which Akonadi event calendars block reminders. Disabled entries are ignored when checking for ongoing events.":
            "Wähle, welche Akonadi-Terminkalender Erinnerungen blockieren. Deaktivierte Einträge werden bei laufenden Terminen ignoriert.",
        "Clear parent": "Übergeordnete Aufgabe entfernen",
        "Click a task": "Auf eine Aufgabe klicken",
        "Collapse subtasks": "Unteraufgaben einklappen",
        "Comfortable": "Komfortabel",
        "Complete only with Shift or Ctrl held": "Nur mit gedrückter Umschalt- oder Strg-Taste abschließen",
        "Completing a parent also completes its children":
            "Abschließen einer übergeordneten Aufgabe schließt auch ihre Unteraufgaben ab",
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "Richte CalDAV/Nextcloud in KOrganizer oder Merkuro ein (DAV-Groupware-Ressource).",
        "Connecting to Akonadi…": "Verbinde mit Akonadi …",
        "Could not load tasks": "Aufgaben konnten nicht geladen werden",
        "Counts": "Zähler",
        "Dates": "Daten",
        "Default due date": "Standard-Fälligkeitsdatum",
        "Default reminder": "Standard-Erinnerung",
        "Delete": "Löschen",
        "Delete task?": "Aufgabe löschen?",
        "Delete this task?": "Diese Aufgabe löschen?",
        "Density": "Dichte",
        "Description preview": "Beschreibungsvorschau",
        "Desktop notifications": "Desktop-Benachrichtigungen",
        "Dot": "Punkt",
        "Due date (latest first)": "Fälligkeitsdatum (neueste zuerst)",
        "During events": "Während Terminen",
        "Each sidebar view keeps its own sort. Views you have not changed start with Priority › Due › Title A–Z.":
            "Jede Seitenleistenansicht behält ihre eigene Sortierung. Unveränderte Ansichten starten mit Priorität › Fälligkeit › Titel A–Z.",
        "Editor": "Editor",
        "Editor dim": "Editor-Abdunkelung",
        "Enable a calendar in Configure Kurrent → Projects, or add a CalDAV resource in Merkuro or KOrganizer.":
            "Aktiviere einen Kalender unter Kurrent konfigurieren → Projekte, oder füge eine CalDAV-Ressource in Merkuro oder KOrganizer hinzu.",
        "Ends": "Endet",
        "Evening": "Abend",
        "Evening starts": "Abend beginnt",
        "Exclude collapsed subtasks from counts": "Eingeklappte Unteraufgaben von Zählern ausschließen",
        "Expand subtasks": "Unteraufgaben ausklappen",
        "First sort": "Erste Sortierung",
        "Heading on the list": "Überschrift in der Liste",
        "Hidden": "Ausgeblendet",
        "High priority": "Hohe Priorität",
        "In 1 hour": "In 1 Stunde",
        "In 15 minutes": "In 15 Minuten",
        "In 4 hours": "In 4 Stunden",
        "Include All": "Alle einbeziehen",
        "Include this calendar when checking for ongoing events":
            "Diesen Kalender bei laufenden Terminen einbeziehen",
        "Light": "Hell",
        "Loading tasks…": "Lade Aufgaben …",
        "Loading…": "Laden …",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "Lege fest, welche beschreibbaren Akonadi-Kalender als Projekte dienen. Deaktivierte Kalender werden beim Laden von Aufgaben vollständig übersprungen. Ausgeblendete Kalender werden geladen, erscheinen aber nicht in der Seitenleiste.",
        "Meetings": "Besprechungen",
        "Morning": "Morgen",
        "Morning starts": "Morgen beginnt",
        "Motion": "Bewegung",
        "No event calendars found. Make sure Akonadi is running and CalDAV calendars are configured.":
            "Keine Terminkalender gefunden. Stelle sicher, dass Akonadi läuft und CalDAV-Kalender eingerichtet sind.",
        "No high priority tasks": "Keine Aufgaben mit hoher Priorität",
        "No matching tasks": "Keine passenden Aufgaben",
        "No overdue tasks": "Keine überfälligen Aufgaben",
        "No task lists": "Keine Aufgabenlisten",
        "No writable Akonadi calendars found. Make sure Akonadi is running and your CalDAV resource allows task edits.":
            "Keine beschreibbaren Akonadi-Kalender gefunden. Stelle sicher, dass Akonadi läuft und deine CalDAV-Ressource Aufgabenbearbeitung erlaubt.",
        "Nothing due today": "Heute nichts fällig",
        "Notifications": "Benachrichtigungen",
        "Notify when a task reminder is due": "Benachrichtigen, wenn eine Aufgabenerinnerung fällig ist",
        "Number": "Zahl",
        "Off": "Aus",
        "One sort order for every view. The default is Priority › Due › Title A–Z until you change it in the task list.":
            "Eine Sortierung für alle Ansichten. Standard ist Priorität › Fälligkeit › Titel A–Z, bis du sie in der Aufgabenliste änderst.",
        "Only opaque (busy) events count. Transparent events are ignored.":
            "Nur undurchsichtige (beschäftigte) Termine zählen. Transparente Termine werden ignoriert.",
        "Open / Join": "Öffnen / Beitreten",
        "Open first": "Offene zuerst",
        "Open root tasks": "Offene Hauptaufgaben",
        "Open tasks": "Offene Aufgaben",
        "Open the full editor": "Vollständigen Editor öffnen",
        "Open the inline editor": "Inline-Editor öffnen",
        "Order and visibility": "Reihenfolge und Sichtbarkeit",
        "Overdue": "Überfällig",
        "Overdue (negative)": "Überfällig (negativ)",
        "Overdue badge color": "Farbe des Überfällig-Badges",
        "Overdue only": "Nur überfällig",
        "Panel": "Panel",
        "Panel badge": "Panel-Badge",
        "Panel tooltip": "Panel-Tooltip",
        "Progress %": "Fortschritt %",
        "Progress % (high first)": "Fortschritt % (hoch zuerst)",
        "Quiet hours": "Ruhezeiten",
        "Recurring first": "Wiederkehrende zuerst",
        "Recurring icon": "Wiederholungs-Symbol",
        "Recurring last": "Wiederkehrende zuletzt",
        "Reduced motion (no spinner, quieter hover)":
            "Reduzierte Bewegung (kein Spinner, dezenteres Hover)",
        "Relative dates (Today, Tomorrow)": "Relative Daten (Heute, Morgen)",
        "Remember globally (all views)": "Global merken (alle Ansichten)",
        "Remember per view": "Pro Ansicht merken",
        "Remember the last view instead": "Stattdessen die letzte Ansicht merken",
        "Reminder first": "Erinnerung zuerst",
        "Reminder last": "Erinnerung zuletzt",
        "Reminder:": "Erinnerung:",
        "Rename": "Umbenennen",
        "Rename from": "Umbenennen von",
        "Rename to": "Umbenennen in",
        "Reset this page": "Diese Seite zurücksetzen",
        "Row chips": "Zeilen-Chips",
        "Row size": "Zeilenhöhe",
        "Search": "Suchen",
        "Search parent task…": "Übergeordnete Aufgabe suchen …",
        "Search titles only": "Nur Titel durchsuchen",
        "Second sort": "Zweite Sortierung",
        "Section:": "Abschnitt:",
        "Sections": "Abschnitte",
        "Select only (double-click opens the full editor)":
            "Nur auswählen (Doppelklick öffnet den vollständigen Editor)",
        "Show a Join button for http(s) links": "Beitritts-Schaltfläche für http(s)-Links anzeigen",
        "Show empty projects": "Leere Projekte anzeigen",
        "Show in the sidebar": "In der Seitenleiste anzeigen",
        "Show overdue tasks at the top of Today": "Überfällige Aufgaben oben in Heute anzeigen",
        "Show task counts": "Aufgabenzähler anzeigen",
        "Show time on the due chip": "Uhrzeit auf dem Fälligkeits-Chip anzeigen",
        "Sidebar": "Seitenleiste",
        "Snooze from the notification (15 minutes, 1 hour, tomorrow) rewrites the VALARM. Due date is unchanged; use Reschedule for that.":
            "Schlummern aus der Benachrichtigung (15 Minuten, 1 Stunde, morgen) schreibt den VALARM um. Das Fälligkeitsdatum bleibt unverändert; dafür „Neu planen“ verwenden.",
        "Sort order": "Sortierreihenfolge",
        "Start date": "Startdatum",
        "Start it with akonadictl start, then add a CalDAV resource in Merkuro or KOrganizer.":
            "Starte es mit akonadictl start und füge dann eine CalDAV-Ressource in Merkuro oder KOrganizer hinzu.",
        "Starts": "Beginnt",
        "Still open": "Noch offen",
        "Strong": "Kräftig",
        "Subtasks": "Unteraufgaben",
        "Suppress reminder notifications in this window": "Erinnerungsbenachrichtigungen in diesem Zeitfenster unterdrücken",
        "Suppress reminders while a calendar event is in progress":
            "Erinnerungen während eines laufenden Kalendertermins unterdrücken",
        "Tasks": "Aufgaben",
        "The flyout is ready; tasks appear when the server answers.":
            "Das Flyout ist bereit; Aufgaben erscheinen, sobald der Server antwortet.",
        "The full editor stays an overlay inside the widget. Day section (LIST) is in the full editor.":
            "Der vollständige Editor bleibt ein Overlay im Widget. Der Tagesabschnitt (LIST) ist im vollständigen Editor.",
        "Third sort": "Dritte Sortierung",
        "Today and overdue": "Heute und überfällig",
        "Today: %1 · Overdue: %2": "Heute: %1 · Überfällig: %2",
        "Try again": "Erneut versuchen",
        "Undo": "Rückgängig",
        "Undo complete": "Abschluss rückgängig",
        "Undo delete": "Löschen rückgängig",
        "Undo move": "Verschieben rückgängig",
        "Undo reschedule": "Neuplanung rückgängig",
        "Views": "Ansichten",
        "Width": "Breite",
    },
    "es": {
        "Kurrent": "Kurrent",
        "Add label": "Añadir etiqueta",
        "%1 grid units": "%1 unidades de cuadrícula",
        "%1:00": "%1:00",
        "1 day before": "1 día antes",
        "1 hour before": "1 hora antes",
        "1 line": "1 línea",
        "15 minutes before": "15 minutos antes",
        "2 lines": "2 líneas",
        "Accent (highlight)": "Acento (resaltado)",
        "Afternoon": "Tarde",
        "Afternoon starts": "La tarde empieza",
        "Akonadi is not running": "Akonadi no está en ejecución",
        "All views": "Todas las vistas",
        "Applies when the badge shows the overdue count.":
            "Se aplica cuando la insignia muestra el recuento de vencidas.",
        "Applies when the badge shows today and there are overdue tasks.":
            "Se aplica cuando la insignia muestra hoy y hay tareas vencidas.",
        "Ask before deleting a task": "Preguntar antes de eliminar una tarea",
        "At due time": "A la hora de vencimiento",
        "Background": "Fondo",
        "Badge display": "Visualización de la insignia",
        "Blurred wallpaper behind the widget": "Fondo de pantalla desenfocado detrás del widget",
        "Calendars for event suppression": "Calendarios para suprimir eventos",
        "Case sensitive": "Distinguir mayúsculas y minúsculas",
        "Catch-up": "Puesta al día",
        "Checkbox": "Casilla",
        "Choose which Akonadi event calendars block reminders. Disabled entries are ignored when checking for ongoing events.":
            "Elige qué calendarios de eventos de Akonadi bloquean recordatorios. Las entradas desactivadas se ignoran al comprobar eventos en curso.",
        "Clear parent": "Quitar tarea principal",
        "Click a task": "Hacer clic en una tarea",
        "Collapse subtasks": "Contraer subtareas",
        "Comfortable": "Cómodo",
        "Complete only with Shift or Ctrl held": "Completar solo con Mayús o Ctrl pulsado",
        "Completing a parent also completes its children":
            "Completar una tarea principal también completa sus subtareas",
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "Configura CalDAV/Nextcloud en KOrganizer o Merkuro (recurso DAV groupware).",
        "Connecting to Akonadi…": "Conectando con Akonadi…",
        "Could not load tasks": "No se pudieron cargar las tareas",
        "Counts": "Recuentos",
        "Dates": "Fechas",
        "Default due date": "Fecha de vencimiento predeterminada",
        "Default reminder": "Recordatorio predeterminado",
        "Delete": "Eliminar",
        "Delete task?": "¿Eliminar tarea?",
        "Delete this task?": "¿Eliminar esta tarea?",
        "Density": "Densidad",
        "Description preview": "Vista previa de la descripción",
        "Desktop notifications": "Notificaciones de escritorio",
        "Dot": "Punto",
        "Due date (latest first)": "Fecha de vencimiento (más reciente primero)",
        "During events": "Durante eventos",
        "Each sidebar view keeps its own sort. Views you have not changed start with Priority › Due › Title A–Z.":
            "Cada vista de la barra lateral conserva su propio orden. Las vistas sin cambios empiezan con Prioridad › Vencimiento › Título A–Z.",
        "Editor": "Editor",
        "Editor dim": "Atenuación del editor",
        "Enable a calendar in Configure Kurrent → Projects, or add a CalDAV resource in Merkuro or KOrganizer.":
            "Activa un calendario en Configurar Kurrent → Proyectos, o añade un recurso CalDAV en Merkuro o KOrganizer.",
        "Ends": "Termina",
        "Evening": "Noche",
        "Evening starts": "La noche empieza",
        "Exclude collapsed subtasks from counts": "Excluir subtareas contraídas de los recuentos",
        "Expand subtasks": "Expandir subtareas",
        "First sort": "Primer orden",
        "Heading on the list": "Encabezado en la lista",
        "Hidden": "Oculto",
        "High priority": "Prioridad alta",
        "In 1 hour": "En 1 hora",
        "In 15 minutes": "En 15 minutos",
        "In 4 hours": "En 4 horas",
        "Include All": "Incluir todo",
        "Include this calendar when checking for ongoing events":
            "Incluir este calendario al comprobar eventos en curso",
        "Light": "Claro",
        "Loading tasks…": "Cargando tareas…",
        "Loading…": "Cargando…",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "Gestiona qué calendarios Akonadi editables se usan como proyectos. Los desactivados no se consultan. Los ocultos se consultan pero no aparecen en la barra lateral.",
        "Meetings": "Reuniones",
        "Morning": "Mañana",
        "Morning starts": "La mañana empieza",
        "Motion": "Movimiento",
        "No event calendars found. Make sure Akonadi is running and CalDAV calendars are configured.":
            "No se encontraron calendarios de eventos. Comprueba que Akonadi esté en ejecución y que los calendarios CalDAV estén configurados.",
        "No high priority tasks": "No hay tareas de prioridad alta",
        "No matching tasks": "No hay tareas coincidentes",
        "No overdue tasks": "No hay tareas vencidas",
        "No task lists": "No hay listas de tareas",
        "No writable Akonadi calendars found. Make sure Akonadi is running and your CalDAV resource allows task edits.":
            "No se encontraron calendarios Akonadi editables. Comprueba que Akonadi esté en ejecución y que tu recurso CalDAV permita editar tareas.",
        "Nothing due today": "Nada vence hoy",
        "Notifications": "Notificaciones",
        "Notify when a task reminder is due": "Notificar cuando venza un recordatorio de tarea",
        "Number": "Número",
        "Off": "Desactivado",
        "One sort order for every view. The default is Priority › Due › Title A–Z until you change it in the task list.":
            "Un orden para todas las vistas. El predeterminado es Prioridad › Vencimiento › Título A–Z hasta que lo cambies en la lista de tareas.",
        "Only opaque (busy) events count. Transparent events are ignored.":
            "Solo cuentan los eventos opacos (ocupados). Los eventos transparentes se ignoran.",
        "Open / Join": "Abrir / Unirse",
        "Open first": "Abiertas primero",
        "Open root tasks": "Tareas principales abiertas",
        "Open tasks": "Tareas abiertas",
        "Open the full editor": "Abrir el editor completo",
        "Open the inline editor": "Abrir el editor en línea",
        "Order and visibility": "Orden y visibilidad",
        "Overdue": "Vencidas",
        "Overdue (negative)": "Vencidas (negativo)",
        "Overdue badge color": "Color de la insignia de vencidas",
        "Overdue only": "Solo vencidas",
        "Panel": "Panel",
        "Panel badge": "Insignia del panel",
        "Panel tooltip": "Información emergente del panel",
        "Progress %": "Progreso %",
        "Progress % (high first)": "Progreso % (alto primero)",
        "Quiet hours": "Horas de silencio",
        "Recurring first": "Recurrentes primero",
        "Recurring icon": "Icono de recurrencia",
        "Recurring last": "Recurrentes al final",
        "Reduced motion (no spinner, quieter hover)":
            "Movimiento reducido (sin indicador, hover más discreto)",
        "Relative dates (Today, Tomorrow)": "Fechas relativas (Hoy, Mañana)",
        "Remember globally (all views)": "Recordar globalmente (todas las vistas)",
        "Remember per view": "Recordar por vista",
        "Remember the last view instead": "Recordar la última vista en su lugar",
        "Reminder first": "Recordatorio primero",
        "Reminder last": "Recordatorio al final",
        "Reminder:": "Recordatorio:",
        "Rename": "Renombrar",
        "Rename from": "Renombrar de",
        "Rename to": "Renombrar a",
        "Reset this page": "Restablecer esta página",
        "Row chips": "Chips de fila",
        "Row size": "Tamaño de fila",
        "Search": "Buscar",
        "Search parent task…": "Buscar tarea principal…",
        "Search titles only": "Buscar solo títulos",
        "Second sort": "Segundo orden",
        "Section:": "Sección:",
        "Sections": "Secciones",
        "Select only (double-click opens the full editor)":
            "Solo seleccionar (doble clic abre el editor completo)",
        "Show a Join button for http(s) links": "Mostrar botón Unirse para enlaces http(s)",
        "Show empty projects": "Mostrar proyectos vacíos",
        "Show in the sidebar": "Mostrar en la barra lateral",
        "Show overdue tasks at the top of Today": "Mostrar tareas vencidas arriba en Hoy",
        "Show task counts": "Mostrar recuentos de tareas",
        "Show time on the due chip": "Mostrar hora en el chip de vencimiento",
        "Sidebar": "Barra lateral",
        "Snooze from the notification (15 minutes, 1 hour, tomorrow) rewrites the VALARM. Due date is unchanged; use Reschedule for that.":
            "Posponer desde la notificación (15 minutos, 1 hora, mañana) reescribe el VALARM. La fecha de vencimiento no cambia; usa Reprogramar para eso.",
        "Sort order": "Orden de clasificación",
        "Start date": "Fecha de inicio",
        "Start it with akonadictl start, then add a CalDAV resource in Merkuro or KOrganizer.":
            "Inícialo con akonadictl start y luego añade un recurso CalDAV en Merkuro o KOrganizer.",
        "Starts": "Empieza",
        "Still open": "Aún abiertas",
        "Strong": "Fuerte",
        "Subtasks": "Subtareas",
        "Suppress reminder notifications in this window": "Suprimir recordatorios en esta franja horaria",
        "Suppress reminders while a calendar event is in progress":
            "Suprimir recordatorios mientras hay un evento de calendario en curso",
        "Tasks": "Tareas",
        "The flyout is ready; tasks appear when the server answers.":
            "El desplegable está listo; las tareas aparecen cuando el servidor responde.",
        "The full editor stays an overlay inside the widget. Day section (LIST) is in the full editor.":
            "El editor completo sigue siendo una superposición dentro del widget. La sección del día (LIST) está en el editor completo.",
        "Third sort": "Tercer orden",
        "Today and overdue": "Hoy y vencidas",
        "Today: %1 · Overdue: %2": "Hoy: %1 · Vencidas: %2",
        "Try again": "Reintentar",
        "Undo": "Deshacer",
        "Undo complete": "Deshacer completado",
        "Undo delete": "Deshacer eliminación",
        "Undo move": "Deshacer movimiento",
        "Undo reschedule": "Deshacer reprogramación",
        "Views": "Vistas",
        "Width": "Ancho",
    },
    "fr": {
        "Kurrent": "Kurrent",
        "Add label": "Ajouter une étiquette",
        "%1 grid units": "%1 unités de grille",
        "%1:00": "%1:00",
        "1 day before": "1 jour avant",
        "1 hour before": "1 heure avant",
        "1 line": "1 ligne",
        "15 minutes before": "15 minutes avant",
        "2 lines": "2 lignes",
        "Accent (highlight)": "Accent (surbrillance)",
        "Afternoon": "Après-midi",
        "Afternoon starts": "L’après-midi commence",
        "Akonadi is not running": "Akonadi n’est pas lancé",
        "All views": "Toutes les vues",
        "Applies when the badge shows the overdue count.":
            "S’applique lorsque le badge affiche le nombre de tâches en retard.",
        "Applies when the badge shows today and there are overdue tasks.":
            "S’applique lorsque le badge affiche Aujourd’hui et qu’il y a des tâches en retard.",
        "Ask before deleting a task": "Demander avant de supprimer une tâche",
        "At due time": "À l’échéance",
        "Background": "Arrière-plan",
        "Badge display": "Affichage du badge",
        "Blurred wallpaper behind the widget": "Fond d’écran flouté derrière le widget",
        "Calendars for event suppression": "Calendriers pour la suppression d’événements",
        "Case sensitive": "Sensible à la casse",
        "Catch-up": "Rattrapage",
        "Checkbox": "Case à cocher",
        "Choose which Akonadi event calendars block reminders. Disabled entries are ignored when checking for ongoing events.":
            "Choisissez quels calendriers d’événements Akonadi bloquent les rappels. Les entrées désactivées sont ignorées lors de la vérification des événements en cours.",
        "Clear parent": "Retirer la tâche parente",
        "Click a task": "Cliquer sur une tâche",
        "Collapse subtasks": "Réduire les sous-tâches",
        "Comfortable": "Confortable",
        "Complete only with Shift or Ctrl held": "Terminer uniquement avec Maj ou Ctrl enfoncé",
        "Completing a parent also completes its children":
            "Terminer une tâche parente termine aussi ses sous-tâches",
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "Configurez CalDAV/Nextcloud dans KOrganizer ou Merkuro (ressource DAV groupware).",
        "Connecting to Akonadi…": "Connexion à Akonadi…",
        "Could not load tasks": "Impossible de charger les tâches",
        "Counts": "Compteurs",
        "Dates": "Dates",
        "Default due date": "Date d’échéance par défaut",
        "Default reminder": "Rappel par défaut",
        "Delete": "Supprimer",
        "Delete task?": "Supprimer la tâche ?",
        "Delete this task?": "Supprimer cette tâche ?",
        "Density": "Densité",
        "Description preview": "Aperçu de la description",
        "Desktop notifications": "Notifications de bureau",
        "Dot": "Point",
        "Due date (latest first)": "Date d’échéance (plus récente d’abord)",
        "During events": "Pendant les événements",
        "Each sidebar view keeps its own sort. Views you have not changed start with Priority › Due › Title A–Z.":
            "Chaque vue de la barre latérale conserve son propre tri. Les vues non modifiées commencent par Priorité › Échéance › Titre A–Z.",
        "Editor": "Éditeur",
        "Editor dim": "Assombrissement de l’éditeur",
        "Enable a calendar in Configure Kurrent → Projects, or add a CalDAV resource in Merkuro or KOrganizer.":
            "Activez un calendrier dans Configurer Kurrent → Projets, ou ajoutez une ressource CalDAV dans Merkuro ou KOrganizer.",
        "Ends": "Se termine",
        "Evening": "Soir",
        "Evening starts": "Le soir commence",
        "Exclude collapsed subtasks from counts": "Exclure les sous-tâches réduites des compteurs",
        "Expand subtasks": "Développer les sous-tâches",
        "First sort": "Premier tri",
        "Heading on the list": "En-tête dans la liste",
        "Hidden": "Masqué",
        "High priority": "Priorité haute",
        "In 1 hour": "Dans 1 heure",
        "In 15 minutes": "Dans 15 minutes",
        "In 4 hours": "Dans 4 heures",
        "Include All": "Tout inclure",
        "Include this calendar when checking for ongoing events":
            "Inclure ce calendrier lors de la vérification des événements en cours",
        "Light": "Clair",
        "Loading tasks…": "Chargement des tâches…",
        "Loading…": "Chargement…",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "Gérez quels calendriers Akonadi modifiables sont utilisés comme projets. Les calendriers désactivés sont exclus. Les calendriers masqués sont chargés mais absents de la barre latérale.",
        "Meetings": "Réunions",
        "Morning": "Matin",
        "Morning starts": "Le matin commence",
        "Motion": "Mouvement",
        "No event calendars found. Make sure Akonadi is running and CalDAV calendars are configured.":
            "Aucun calendrier d’événements trouvé. Vérifiez qu’Akonadi est lancé et que les calendriers CalDAV sont configurés.",
        "No high priority tasks": "Aucune tâche à priorité haute",
        "No matching tasks": "Aucune tâche correspondante",
        "No overdue tasks": "Aucune tâche en retard",
        "No task lists": "Aucune liste de tâches",
        "No writable Akonadi calendars found. Make sure Akonadi is running and your CalDAV resource allows task edits.":
            "Aucun calendrier Akonadi modifiable trouvé. Vérifiez qu’Akonadi est lancé et que votre ressource CalDAV autorise la modification des tâches.",
        "Nothing due today": "Rien à échéance aujourd’hui",
        "Notifications": "Notifications",
        "Notify when a task reminder is due": "Notifier lorsqu’un rappel de tâche est dû",
        "Number": "Nombre",
        "Off": "Désactivé",
        "One sort order for every view. The default is Priority › Due › Title A–Z until you change it in the task list.":
            "Un ordre de tri pour toutes les vues. Par défaut : Priorité › Échéance › Titre A–Z jusqu’à modification dans la liste des tâches.",
        "Only opaque (busy) events count. Transparent events are ignored.":
            "Seuls les événements opaques (occupés) comptent. Les événements transparents sont ignorés.",
        "Open / Join": "Ouvrir / Rejoindre",
        "Open first": "Ouvertes d’abord",
        "Open root tasks": "Tâches principales ouvertes",
        "Open tasks": "Tâches ouvertes",
        "Open the full editor": "Ouvrir l’éditeur complet",
        "Open the inline editor": "Ouvrir l’éditeur en ligne",
        "Order and visibility": "Ordre et visibilité",
        "Overdue": "En retard",
        "Overdue (negative)": "En retard (négatif)",
        "Overdue badge color": "Couleur du badge de retard",
        "Overdue only": "Retard uniquement",
        "Panel": "Panneau",
        "Panel badge": "Badge du panneau",
        "Panel tooltip": "Infobulle du panneau",
        "Progress %": "Progression %",
        "Progress % (high first)": "Progression % (élevée d’abord)",
        "Quiet hours": "Heures calmes",
        "Recurring first": "Récurrentes d’abord",
        "Recurring icon": "Icône de récurrence",
        "Recurring last": "Récurrentes en dernier",
        "Reduced motion (no spinner, quieter hover)":
            "Mouvement réduit (pas d’indicateur, survol plus discret)",
        "Relative dates (Today, Tomorrow)": "Dates relatives (Aujourd’hui, Demain)",
        "Remember globally (all views)": "Mémoriser globalement (toutes les vues)",
        "Remember per view": "Mémoriser par vue",
        "Remember the last view instead": "Mémoriser la dernière vue à la place",
        "Reminder first": "Rappel d’abord",
        "Reminder last": "Rappel en dernier",
        "Reminder:": "Rappel :",
        "Rename": "Renommer",
        "Rename from": "Renommer depuis",
        "Rename to": "Renommer en",
        "Reset this page": "Réinitialiser cette page",
        "Row chips": "Pastilles de ligne",
        "Row size": "Taille des lignes",
        "Search": "Rechercher",
        "Search parent task…": "Rechercher une tâche parente…",
        "Search titles only": "Rechercher uniquement les titres",
        "Second sort": "Deuxième tri",
        "Section:": "Section :",
        "Sections": "Sections",
        "Select only (double-click opens the full editor)":
            "Sélectionner uniquement (double-clic ouvre l’éditeur complet)",
        "Show a Join button for http(s) links": "Afficher un bouton Rejoindre pour les liens http(s)",
        "Show empty projects": "Afficher les projets vides",
        "Show in the sidebar": "Afficher dans la barre latérale",
        "Show overdue tasks at the top of Today": "Afficher les tâches en retard en haut d’Aujourd’hui",
        "Show task counts": "Afficher les compteurs de tâches",
        "Show time on the due chip": "Afficher l’heure sur la pastille d’échéance",
        "Sidebar": "Barre latérale",
        "Snooze from the notification (15 minutes, 1 hour, tomorrow) rewrites the VALARM. Due date is unchanged; use Reschedule for that.":
            "Reporter depuis la notification (15 minutes, 1 heure, demain) réécrit le VALARM. La date d’échéance reste inchangée ; utilisez Replanifier pour cela.",
        "Sort order": "Ordre de tri",
        "Start date": "Date de début",
        "Start it with akonadictl start, then add a CalDAV resource in Merkuro or KOrganizer.":
            "Lancez-le avec akonadictl start, puis ajoutez une ressource CalDAV dans Merkuro ou KOrganizer.",
        "Starts": "Commence",
        "Still open": "Encore ouvertes",
        "Strong": "Fort",
        "Subtasks": "Sous-tâches",
        "Suppress reminder notifications in this window": "Supprimer les rappels dans cette plage horaire",
        "Suppress reminders while a calendar event is in progress":
            "Supprimer les rappels pendant un événement de calendrier en cours",
        "Tasks": "Tâches",
        "The flyout is ready; tasks appear when the server answers.":
            "Le menu est prêt ; les tâches apparaissent lorsque le serveur répond.",
        "The full editor stays an overlay inside the widget. Day section (LIST) is in the full editor.":
            "L’éditeur complet reste une superposition dans le widget. La section du jour (LIST) est dans l’éditeur complet.",
        "Third sort": "Troisième tri",
        "Today and overdue": "Aujourd’hui et en retard",
        "Today: %1 · Overdue: %2": "Aujourd’hui : %1 · En retard : %2",
        "Try again": "Réessayer",
        "Undo": "Annuler",
        "Undo complete": "Annuler la complétion",
        "Undo delete": "Annuler la suppression",
        "Undo move": "Annuler le déplacement",
        "Undo reschedule": "Annuler la replanification",
        "Views": "Vues",
        "Width": "Largeur",
    },
    "ja": {
        "%1 grid units": "%1 グリッド単位",
        "%1:00": "%1:00",
        "1 day before": "1日前",
        "1 hour before": "1時間前",
        "1 line": "1行",
        "15 minutes before": "15分前",
        "2 lines": "2行",
        "Accent (highlight)": "アクセント（ハイライト）",
        "Afternoon": "午後",
        "Afternoon starts": "午後の開始",
        "Akonadi is not running": "Akonadi が実行されていません",
        "All views": "すべてのビュー",
        "Applies when the badge shows the overdue count.":
            "バッジが期限超過の件数を表示するときに適用されます。",
        "Applies when the badge shows today and there are overdue tasks.":
            "バッジが今日を表示し、期限超過のタスクがあるときに適用されます。",
        "Ask before deleting a task": "タスク削除前に確認する",
        "At due time": "期限時刻",
        "Background": "背景",
        "Badge display": "バッジ表示",
        "Blurred wallpaper behind the widget": "ウィジェット背面の壁紙ぼかし",
        "Calendars for event suppression": "イベント抑制用カレンダー",
        "Case sensitive": "大文字と小文字を区別",
        "Catch-up": "キャッチアップ",
        "Checkbox": "チェックボックス",
        "Choose which Akonadi event calendars block reminders. Disabled entries are ignored when checking for ongoing events.":
            "どの Akonadi イベントカレンダーがリマインダーをブロックするか選びます。無効な項目は進行中イベントの確認時に無視されます。",
        "Clear parent": "親タスクを解除",
        "Click a task": "タスクをクリック",
        "Collapse subtasks": "サブタスクを折りたたむ",
        "Comfortable": "ゆったり",
        "Complete only with Shift or Ctrl held": "Shift または Ctrl を押したときのみ完了",
        "Completing a parent also completes its children":
            "親タスクを完了すると子タスクも完了します",
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "KOrganizer または Merkuro で CalDAV/Nextcloud を設定してください（DAV グループウェアリソース）。",
        "Connecting to Akonadi…": "Akonadi に接続中…",
        "Could not load tasks": "タスクを読み込めませんでした",
        "Counts": "件数",
        "Dates": "日付",
        "Default due date": "デフォルトの期限",
        "Default reminder": "デフォルトのリマインダー",
        "Delete": "削除",
        "Delete task?": "タスクを削除しますか？",
        "Delete this task?": "このタスクを削除しますか？",
        "Density": "密度",
        "Description preview": "説明のプレビュー",
        "Desktop notifications": "デスクトップ通知",
        "Dot": "ドット",
        "Due date (latest first)": "期限（新しい順）",
        "During events": "イベント中",
        "Each sidebar view keeps its own sort. Views you have not changed start with Priority › Due › Title A–Z.":
            "各サイドバービューは独自の並べ替えを保持します。変更していないビューは優先度 › 期限 › タイトル A–Z から始まります。",
        "Editor": "エディター",
        "Editor dim": "エディターの暗転",
        "Enable a calendar in Configure Kurrent → Projects, or add a CalDAV resource in Merkuro or KOrganizer.":
            "Kurrent の設定 → プロジェクトでカレンダーを有効にするか、Merkuro または KOrganizer で CalDAV リソースを追加してください。",
        "Ends": "終了",
        "Evening": "夕方",
        "Evening starts": "夕方の開始",
        "Exclude collapsed subtasks from counts": "折りたたんだサブタスクを件数から除外",
        "Expand subtasks": "サブタスクを展開",
        "First sort": "第1ソート",
        "Heading on the list": "リストの見出し",
        "Hidden": "非表示",
        "High priority": "優先度高",
        "In 1 hour": "1時間後",
        "In 15 minutes": "15分後",
        "In 4 hours": "4時間後",
        "Include All": "すべて含める",
        "Include this calendar when checking for ongoing events":
            "進行中イベントの確認時にこのカレンダーを含める",
        "Light": "ライト",
        "Loading tasks…": "タスクを読み込み中…",
        "Loading…": "読み込み中…",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "プロジェクトとして使う書き込み可能な Akonadi カレンダーを管理します。無効なカレンダーはタスク取得から除外されます。非表示のカレンダーは取得されますが、サイドバーには表示されません。",
        "Meetings": "会議",
        "Morning": "朝",
        "Morning starts": "朝の開始",
        "Motion": "モーション",
        "No event calendars found. Make sure Akonadi is running and CalDAV calendars are configured.":
            "イベントカレンダーが見つかりません。Akonadi が起動していることと CalDAV カレンダーが設定されていることを確認してください。",
        "No high priority tasks": "優先度の高いタスクはありません",
        "No matching tasks": "一致するタスクはありません",
        "No overdue tasks": "期限超過のタスクはありません",
        "No task lists": "タスクリストがありません",
        "No writable Akonadi calendars found. Make sure Akonadi is running and your CalDAV resource allows task edits.":
            "書き込み可能な Akonadi カレンダーが見つかりません。Akonadi が起動していることと CalDAV リソースがタスク編集を許可していることを確認してください。",
        "Nothing due today": "今日は期限なし",
        "Notifications": "通知",
        "Notify when a task reminder is due": "タスクリマインダーの期限時に通知",
        "Number": "数字",
        "Off": "オフ",
        "One sort order for every view. The default is Priority › Due › Title A–Z until you change it in the task list.":
            "すべてのビューで同じ並べ替えです。タスクリストで変更するまで、デフォルトは優先度 › 期限 › タイトル A–Z です。",
        "Only opaque (busy) events count. Transparent events are ignored.":
            "不透明（予定あり）のイベントのみ対象です。透明なイベントは無視されます。",
        "Open / Join": "開く / 参加",
        "Open first": "未完了優先",
        "Open root tasks": "未完了のルートタスク",
        "Open tasks": "未完了タスク",
        "Open the full editor": "フルエディターを開く",
        "Open the inline editor": "インラインエディターを開く",
        "Order and visibility": "順序と表示",
        "Overdue": "期限超過",
        "Overdue (negative)": "期限超過（ネガティブ）",
        "Overdue badge color": "期限超過バッジの色",
        "Overdue only": "期限超過のみ",
        "Panel": "パネル",
        "Panel badge": "パネルバッジ",
        "Panel tooltip": "パネルのツールチップ",
        "Progress %": "進捗 %",
        "Progress % (high first)": "進捗 %（高い順）",
        "Quiet hours": "おやすみ時間",
        "Recurring first": "繰り返し優先",
        "Recurring icon": "繰り返しアイコン",
        "Recurring last": "繰り返し最後",
        "Reduced motion (no spinner, quieter hover)":
            "モーション低減（スピナーなし、控えめなホバー）",
        "Relative dates (Today, Tomorrow)": "相対日付（今日、明日）",
        "Remember globally (all views)": "全体で記憶（すべてのビュー）",
        "Remember per view": "ビューごとに記憶",
        "Remember the last view instead": "代わりに最後のビューを記憶",
        "Reminder first": "リマインダー優先",
        "Reminder last": "リマインダー最後",
        "Reminder:": "リマインダー:",
        "Rename": "名前を変更",
        "Rename from": "変更前",
        "Rename to": "変更後",
        "Reset this page": "このページをリセット",
        "Row chips": "行チップ",
        "Row size": "行の高さ",
        "Search": "検索",
        "Search parent task…": "親タスクを検索…",
        "Search titles only": "タイトルのみ検索",
        "Second sort": "第2ソート",
        "Section:": "セクション:",
        "Sections": "セクション",
        "Select only (double-click opens the full editor)":
            "選択のみ（ダブルクリックでフルエディター）",
        "Show a Join button for http(s) links": "http(s) リンクに参加ボタンを表示",
        "Show empty projects": "空のプロジェクトを表示",
        "Show in the sidebar": "サイドバーに表示",
        "Show overdue tasks at the top of Today": "今日の先頭に期限超過タスクを表示",
        "Show task counts": "タスク件数を表示",
        "Show time on the due chip": "期限チップに時刻を表示",
        "Sidebar": "サイドバー",
        "Snooze from the notification (15 minutes, 1 hour, tomorrow) rewrites the VALARM. Due date is unchanged; use Reschedule for that.":
            "通知からのスヌーズ（15分、1時間、明日）は VALARM を書き換えます。期限は変わりません。期限変更には再スケジュールを使ってください。",
        "Sort order": "並べ替え順",
        "Start date": "開始日",
        "Start it with akonadictl start, then add a CalDAV resource in Merkuro or KOrganizer.":
            "akonadictl start で起動し、Merkuro または KOrganizer で CalDAV リソースを追加してください。",
        "Starts": "開始",
        "Still open": "まだ未完了",
        "Strong": "強調",
        "Subtasks": "サブタスク",
        "Suppress reminder notifications in this window": "この時間帯のリマインダー通知を抑制",
        "Suppress reminders while a calendar event is in progress":
            "カレンダーイベント進行中はリマインダーを抑制",
        "Tasks": "タスク",
        "The flyout is ready; tasks appear when the server answers.":
            "フライアウトの準備完了。サーバー応答後にタスクが表示されます。",
        "The full editor stays an overlay inside the widget. Day section (LIST) is in the full editor.":
            "フルエディターはウィジェット内のオーバーレイのままです。日セクション（LIST）はフルエディター内にあります。",
        "Third sort": "第3ソート",
        "Today and overdue": "今日と期限超過",
        "Today: %1 · Overdue: %2": "今日: %1 · 期限超過: %2",
        "Try again": "再試行",
        "Undo": "元に戻す",
        "Undo complete": "完了を元に戻す",
        "Undo delete": "削除を元に戻す",
        "Undo move": "移動を元に戻す",
        "Undo reschedule": "再スケジュールを元に戻す",
        "Views": "ビュー",
        "Width": "幅",
    },
    "zh_CN": {
        "Kurrent": "Kurrent",
        "Add label": "添加标签",
        "%1 grid units": "%1 格单位",
        "%1:00": "%1:00",
        "1 day before": "提前 1 天",
        "1 hour before": "提前 1 小时",
        "1 line": "1 行",
        "15 minutes before": "提前 15 分钟",
        "2 lines": "2 行",
        "Accent (highlight)": "强调色（高亮）",
        "Afternoon": "下午",
        "Afternoon starts": "下午开始",
        "Akonadi is not running": "Akonadi 未运行",
        "All views": "所有视图",
        "Applies when the badge shows the overdue count.":
            "适用于徽章显示逾期数量时。",
        "Applies when the badge shows today and there are overdue tasks.":
            "适用于徽章显示今天且存在逾期任务时。",
        "Ask before deleting a task": "删除任务前询问",
        "At due time": "到期时",
        "Background": "背景",
        "Badge display": "徽章显示",
        "Blurred wallpaper behind the widget": "部件背后的模糊壁纸",
        "Calendars for event suppression": "用于抑制事件的日历",
        "Case sensitive": "区分大小写",
        "Catch-up": "补做",
        "Checkbox": "复选框",
        "Choose which Akonadi event calendars block reminders. Disabled entries are ignored when checking for ongoing events.":
            "选择哪些 Akonadi 事件日历会阻止提醒。检查进行中的事件时会忽略已禁用的条目。",
        "Clear parent": "清除父任务",
        "Click a task": "点击任务",
        "Collapse subtasks": "折叠子任务",
        "Comfortable": "舒适",
        "Complete only with Shift or Ctrl held": "仅按住 Shift 或 Ctrl 时完成",
        "Completing a parent also completes its children":
            "完成父任务也会完成其子任务",
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "在 KOrganizer 或 Merkuro 中配置 CalDAV/Nextcloud（DAV 群件资源）。",
        "Connecting to Akonadi…": "正在连接 Akonadi…",
        "Could not load tasks": "无法加载任务",
        "Counts": "计数",
        "Dates": "日期",
        "Default due date": "默认截止日期",
        "Default reminder": "默认提醒",
        "Delete": "删除",
        "Delete task?": "删除任务？",
        "Delete this task?": "删除此任务？",
        "Density": "密度",
        "Description preview": "描述预览",
        "Desktop notifications": "桌面通知",
        "Dot": "圆点",
        "Due date (latest first)": "截止日期（最新优先）",
        "During events": "事件期间",
        "Each sidebar view keeps its own sort. Views you have not changed start with Priority › Due › Title A–Z.":
            "每个侧栏视图保留各自的排序。未更改的视图默认以优先级 › 截止 › 标题 A–Z 开始。",
        "Editor": "编辑器",
        "Editor dim": "编辑器遮罩",
        "Enable a calendar in Configure Kurrent → Projects, or add a CalDAV resource in Merkuro or KOrganizer.":
            "在配置 Kurrent → 项目中启用日历，或在 Merkuro 或 KOrganizer 中添加 CalDAV 资源。",
        "Ends": "结束",
        "Evening": "晚上",
        "Evening starts": "晚上开始",
        "Exclude collapsed subtasks from counts": "计数时排除已折叠的子任务",
        "Expand subtasks": "展开子任务",
        "First sort": "第一排序",
        "Heading on the list": "列表标题",
        "Hidden": "隐藏",
        "High priority": "高优先级",
        "In 1 hour": "1 小时后",
        "In 15 minutes": "15 分钟后",
        "In 4 hours": "4 小时后",
        "Include All": "全部包含",
        "Include this calendar when checking for ongoing events":
            "检查进行中的事件时包含此日历",
        "Light": "浅色",
        "Loading tasks…": "正在加载任务…",
        "Loading…": "正在加载…",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "管理哪些可写的 Akonadi 日历用作项目。禁用的日历完全不获取任务。隐藏的日历仍会获取，但不在侧栏显示。",
        "Meetings": "会议",
        "Morning": "上午",
        "Morning starts": "上午开始",
        "Motion": "动效",
        "No event calendars found. Make sure Akonadi is running and CalDAV calendars are configured.":
            "未找到事件日历。请确认 Akonadi 正在运行且已配置 CalDAV 日历。",
        "No high priority tasks": "没有高优先级任务",
        "No matching tasks": "没有匹配的任务",
        "No overdue tasks": "没有逾期任务",
        "No task lists": "没有任务列表",
        "No writable Akonadi calendars found. Make sure Akonadi is running and your CalDAV resource allows task edits.":
            "未找到可写的 Akonadi 日历。请确认 Akonadi 正在运行且 CalDAV 资源允许编辑任务。",
        "Nothing due today": "今天无到期任务",
        "Notifications": "通知",
        "Notify when a task reminder is due": "任务提醒到期时通知",
        "Number": "数字",
        "Off": "关闭",
        "One sort order for every view. The default is Priority › Due › Title A–Z until you change it in the task list.":
            "所有视图使用同一排序。在任务列表中更改前，默认为优先级 › 截止 › 标题 A–Z。",
        "Only opaque (busy) events count. Transparent events are ignored.":
            "仅不透明（忙碌）事件计入。透明事件会被忽略。",
        "Open / Join": "打开 / 加入",
        "Open first": "未完成优先",
        "Open root tasks": "未完成的根任务",
        "Open tasks": "未完成任务",
        "Open the full editor": "打开完整编辑器",
        "Open the inline editor": "打开内联编辑器",
        "Order and visibility": "顺序和可见性",
        "Overdue": "逾期",
        "Overdue (negative)": "逾期（负色）",
        "Overdue badge color": "逾期徽章颜色",
        "Overdue only": "仅逾期",
        "Panel": "面板",
        "Panel badge": "面板徽章",
        "Panel tooltip": "面板提示",
        "Progress %": "进度 %",
        "Progress % (high first)": "进度 %（高优先）",
        "Quiet hours": "免打扰时段",
        "Recurring first": "重复优先",
        "Recurring icon": "重复图标",
        "Recurring last": "重复最后",
        "Reduced motion (no spinner, quieter hover)":
            "减少动效（无加载动画，更安静的悬停）",
        "Relative dates (Today, Tomorrow)": "相对日期（今天、明天）",
        "Remember globally (all views)": "全局记住（所有视图）",
        "Remember per view": "按视图记住",
        "Remember the last view instead": "改为记住上次视图",
        "Reminder first": "提醒优先",
        "Reminder last": "提醒最后",
        "Reminder:": "提醒：",
        "Rename": "重命名",
        "Rename from": "原名称",
        "Rename to": "新名称",
        "Reset this page": "重置此页",
        "Row chips": "行标签",
        "Row size": "行高",
        "Search": "搜索",
        "Search parent task…": "搜索父任务…",
        "Search titles only": "仅搜索标题",
        "Second sort": "第二排序",
        "Section:": "分区：",
        "Sections": "分区",
        "Select only (double-click opens the full editor)":
            "仅选择（双击打开完整编辑器）",
        "Show a Join button for http(s) links": "为 http(s) 链接显示加入按钮",
        "Show empty projects": "显示空项目",
        "Show in the sidebar": "在侧栏显示",
        "Show overdue tasks at the top of Today": "在今天视图顶部显示逾期任务",
        "Show task counts": "显示任务计数",
        "Show time on the due chip": "在截止标签上显示时间",
        "Sidebar": "侧栏",
        "Snooze from the notification (15 minutes, 1 hour, tomorrow) rewrites the VALARM. Due date is unchanged; use Reschedule for that.":
            "从通知推迟（15 分钟、1 小时、明天）会重写 VALARM。截止日期不变；请使用重新安排。",
        "Sort order": "排序方式",
        "Start date": "开始日期",
        "Start it with akonadictl start, then add a CalDAV resource in Merkuro or KOrganizer.":
            "使用 akonadictl start 启动，然后在 Merkuro 或 KOrganizer 中添加 CalDAV 资源。",
        "Starts": "开始",
        "Still open": "仍未完成",
        "Strong": "醒目",
        "Subtasks": "子任务",
        "Suppress reminder notifications in this window": "在此时间段内抑制提醒通知",
        "Suppress reminders while a calendar event is in progress":
            "日历事件进行中时抑制提醒",
        "Tasks": "任务",
        "The flyout is ready; tasks appear when the server answers.":
            "弹出窗口已就绪；服务器响应后显示任务。",
        "The full editor stays an overlay inside the widget. Day section (LIST) is in the full editor.":
            "完整编辑器仍为部件内的叠加层。日分区（LIST）在完整编辑器中。",
        "Third sort": "第三排序",
        "Today and overdue": "今天和逾期",
        "Today: %1 · Overdue: %2": "今天：%1 · 逾期：%2",
        "Try again": "重试",
        "Undo": "撤销",
        "Undo complete": "撤销完成",
        "Undo delete": "撤销删除",
        "Undo move": "撤销移动",
        "Undo reschedule": "撤销重新安排",
        "Views": "视图",
        "Width": "宽度",
    },
}

# Override stale catalog strings that differ from current QML source.
OVERRIDES = {
    "de": {
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "Richte CalDAV/Nextcloud in KOrganizer oder Merkuro ein (DAV-Groupware-Ressource).",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "Lege fest, welche beschreibbaren Akonadi-Kalender als Projekte dienen. Deaktivierte Kalender werden beim Laden von Aufgaben vollständig übersprungen. Ausgeblendete Kalender werden geladen, erscheinen aber nicht in der Seitenleiste.",
        "Blurred wallpaper behind the widget":
            "Unscharfes Hintergrundbild hinter dem Widget",
        "Comfortable": "Komfortabel",
    },
    "ja": {
        "Configure CalDAV/Nextcloud in KOrganizer or Merkuro (DAV groupware resource).":
            "KOrganizer または Merkuro で CalDAV/Nextcloud を設定してください（DAV グループウェアリソース）。",
        "Manage which writable Akonadi calendars are used as projects. Disabled calendars are excluded from task fetching entirely. Hidden calendars are still fetched but not shown in the sidebar.":
            "プロジェクトとして使う書き込み可能な Akonadi カレンダーを管理します。無効なカレンダーはタスク取得から除外されます。非表示のカレンダーは取得されますが、サイドバーには表示されません。",
    },
}
