"""Gaps found in the redesign review (settings pages, smart views, heatmap, calendar) — merged by _merge_catalog.py.

Each row: msgid (as written in QML, escapes kept), de, es, fr, ja, zh_CN. None = keep the existing translation.
"""

_ROWS = [
    ('%1 %2 on %3', '%1 %2 am %3', '%1 %2 el %3', '%1 %2 le %3', '%3: %1 %2', '%3：%1 %2'),
    ('0 = show all time periods', '0 = alle Zeiträume anzeigen', '0 = mostrar todos los periodos', '0 = afficher toutes les périodes', '0 = すべての期間を表示', '0 = 显示所有时间段'),
    ('0–25%', '0–25 %', '0–25 %', '0–25 %', '0–25%', '0–25%'),
    ('26–50%', '26–50 %', '26–50 %', '26–50 %', '26–50%', '26–50%'),
    ('51–75%', '51–75 %', '51–75 %', '51–75 %', '51–75%', '51–75%'),
    ('76–100%', '76–100 %', '76–100 %', '76–100 %', '76–100%', '76–100%'),
    ('Add location', 'Ort hinzufügen', 'Añadir ubicación', 'Ajouter un lieu', '場所を追加', '添加地点'),
    ('Agenda', 'Agenda', 'Agenda', 'Agenda', 'アジェンダ', '日程'),
    ('Assignees', 'Zuständige', 'Asignados', 'Responsables', '担当者', '负责人'),
    ('Back', 'Zurück', 'Atrás', 'Retour', '戻る', '返回'),
    ('Both use com.github.shrippen.kurrent.akonadi. Info covers writes and sync (Qt Info). Verbose adds fetch/monitor lines (Qt Debug).',
     'Beide nutzen com.github.shrippen.kurrent.akonadi. Info umfasst Schreibvorgänge und Sync (Qt Info). Ausführlich ergänzt Abruf- und Monitorzeilen (Qt Debug).',
     'Ambos usan com.github.shrippen.kurrent.akonadi. Info cubre escrituras y sincronización (Qt Info). Detallado añade líneas de obtención y monitor (Qt Debug).',
     'Les deux utilisent com.github.shrippen.kurrent.akonadi. Info couvre les écritures et la synchro (Qt Info). Détaillé ajoute les lignes de récupération et de suivi (Qt Debug).',
     'どちらも com.github.shrippen.kurrent.akonadi を使用します。情報は書き込みと同期 (Qt Info)、詳細は取得・監視の行 (Qt Debug) を追加します。',
     '两者均使用 com.github.shrippen.kurrent.akonadi。信息包含写入和同步 (Qt Info)，详细另含获取/监视日志 (Qt Debug)。'),
    ('Category', 'Kategorie', 'Categoría', 'Catégorie', 'カテゴリ', '类别'),
    ('Choose calendars', 'Kalender wählen', 'Elegir calendarios', 'Choisir les agendas', 'カレンダーを選択', '选择日历'),
    ('Choose how this Smart View looks and sorts tasks.', 'Lege fest, wie diese Smart View aussieht und Aufgaben sortiert.', 'Elige cómo se ve esta vista inteligente y cómo ordena las tareas.', 'Choisissez l’apparence de cette vue intelligente et le tri des tâches.', 'このスマートビューの表示と並べ替えを選択します。', '选择此智能视图的外观和任务排序方式。'),
    ('Clear location', 'Ort entfernen', 'Quitar ubicación', 'Effacer le lieu', '場所をクリア', '清除地点'),
    ('Clear location “%1”', 'Ort „%1“ entfernen', 'Quitar ubicación «%1»', 'Effacer le lieu « %1 »', '場所「%1」をクリア', '清除地点“%1”'),
    ('Column axis', 'Spaltenachse', 'Eje de columnas', 'Axe des colonnes', '列の軸', '列轴'),
    ('Create label \\u201c%1\\u201d', 'Label „%1“ anlegen', 'Crear etiqueta «%1»', 'Créer l’étiquette « %1 »', 'ラベル「%1」を作成', '创建标签“%1”'),
    ('Day section (morning / afternoon / …)', 'Tagesabschnitt (Morgen / Nachmittag / …)', 'Parte del día (mañana / tarde / …)', 'Moment de la journée (matin / après-midi / …)', '時間帯 (朝 / 午後 / …)', '时段（上午 / 下午 / …）'),
    ('Days side by side', 'Tage nebeneinander', 'Días lado a lado', 'Jours côte à côte', '日を横に並べる', '日期并排'),
    ('Days stacked', 'Tage untereinander', 'Días apilados', 'Jours empilés', '日を縦に並べる', '日期堆叠'),
    ('Delete location', 'Ort löschen', 'Eliminar ubicación', 'Supprimer le lieu', '場所を削除', '删除地点'),
    ('Drop here', 'Hier ablegen', 'Soltar aquí', 'Déposer ici', 'ここにドロップ', '拖放到此处'),
    ('Due date:', 'Fälligkeit:', 'Vencimiento:', 'Échéance :', '期限:', '截止日期：'),
    ('Few', 'Wenige', 'Pocas', 'Peu', '少', '少'),
    ('Filter by KURRENT/LIST day section. Used by the Today view to group tasks into Morning, Afternoon, and Evening buckets.',
     'Nach Tagesabschnitt (KURRENT/LIST) filtern. Die Heute-Ansicht gruppiert damit Aufgaben in Morgen, Nachmittag und Abend.',
     'Filtrar por parte del día (KURRENT/LIST). La vista Hoy la usa para agrupar tareas en mañana, tarde y noche.',
     'Filtrer par moment de la journée (KURRENT/LIST). La vue Aujourd’hui s’en sert pour grouper les tâches en matin, après-midi et soir.',
     '時間帯 (KURRENT/LIST) で絞り込みます。今日ビューで朝・午後・夜に分けるのに使います。',
     '按时段（KURRENT/LIST）筛选。“今天”视图用它把任务分为上午、下午和晚上。'),
    ('Filter by a custom KURRENT/COLUMN value. Only needed when using Kanban with \\"Custom column\\" as source. Leave empty to ignore.',
     'Nach eigenem KURRENT/COLUMN-Wert filtern. Nur nötig, wenn Kanban „Eigene Spalte“ als Quelle nutzt. Leer lassen, um zu ignorieren.',
     'Filtrar por un valor propio de KURRENT/COLUMN. Solo hace falta si el Kanban usa «Columna propia» como origen. Déjalo vacío para ignorarlo.',
     'Filtrer par une valeur KURRENT/COLUMN personnalisée. Utile seulement si le Kanban utilise « Colonne personnalisée » comme source. Laisser vide pour ignorer.',
     '独自の KURRENT/COLUMN 値で絞り込みます。カンバンのソースが「カスタム列」の場合のみ必要です。空欄で無視します。',
     '按自定义 KURRENT/COLUMN 值筛选。仅当看板以“自定义列”为来源时需要。留空则忽略。'),
    ('Filter by priority level. \\"Any priority\\" shows all tasks.', 'Nach Priorität filtern. „Beliebige Priorität“ zeigt alle Aufgaben.', 'Filtrar por prioridad. «Cualquier prioridad» muestra todas las tareas.', 'Filtrer par priorité. « Toute priorité » affiche toutes les tâches.', '優先度で絞り込みます。「すべての優先度」ですべて表示します。', '按优先级筛选。“任意优先级”显示所有任务。'),
    ('Filter by task status. \\"Any status\\" shows tasks regardless of status.', 'Nach Status filtern. „Beliebiger Status“ zeigt Aufgaben unabhängig vom Status.', 'Filtrar por estado. «Cualquier estado» muestra las tareas sin importar su estado.', 'Filtrer par statut. « Tout statut » affiche les tâches quel que soit leur statut.', '状態で絞り込みます。「すべての状態」で状態に関係なく表示します。', '按状态筛选。“任意状态”显示所有状态的任务。'),
    ('Filter tasks by when they are due. \\"Any due date\\" shows all regardless of due date.', 'Nach Fälligkeit filtern. „Beliebige Fälligkeit“ zeigt alle unabhängig vom Datum.', 'Filtrar por vencimiento. «Cualquier vencimiento» muestra todas sin importar la fecha.', 'Filtrer par échéance. « Toute échéance » affiche tout, quelle que soit la date.', '期限で絞り込みます。「すべての期限」で期限に関係なく表示します。', '按截止时间筛选。“任意截止日期”显示所有任务。'),
    ('Filter tasks whose title or description contains this text. Leave empty to show all.', 'Aufgaben filtern, deren Titel oder Beschreibung diesen Text enthält. Leer lassen, um alle zu zeigen.', 'Filtrar tareas cuyo título o descripción contenga este texto. Déjalo vacío para mostrar todas.', 'Filtrer les tâches dont le titre ou la description contient ce texte. Laisser vide pour tout afficher.', 'タイトルか説明にこの文字列を含むタスクに絞り込みます。空欄ですべて表示します。', '筛选标题或描述包含此文本的任务。留空显示全部。'),
    ('Fr', 'Fr', 'vi', 've', '金', '五'),
    ('Group tasks', 'Aufgaben gruppieren', 'Agrupar tareas', 'Grouper les tâches', 'タスクをグループ化', '任务分组'),
    ('Group: %1', 'Gruppe: %1', 'Grupo: %1', 'Groupe : %1', 'グループ: %1', '分组：%1'),
    ('Has no location', 'Ohne Ort', 'Sin ubicación', 'Sans lieu', '場所なし', '无地点'),
    ('Has reminder', 'Mit Erinnerung', 'Con recordatorio', 'Avec rappel', 'リマインダーあり', '有提醒'),
    ('How tasks are ordered in this view. Leave at Default to use Priority → Due → Title.', 'Reihenfolge der Aufgaben in dieser Ansicht. „Standard“ sortiert nach Priorität → Fälligkeit → Titel.', 'Orden de las tareas en esta vista. «Predeterminado» usa Prioridad → Vencimiento → Título.', 'Ordre des tâches dans cette vue. « Par défaut » trie par Priorité → Échéance → Titre.', 'このビューでの並び順です。「既定」では優先度 → 期限 → タイトルの順です。', '此视图中任务的排序方式。“默认”按 优先级 → 截止 → 标题 排序。'),
    ('Icon displayed next to the Smart View in the sidebar.', 'Symbol neben der Smart View in der Seitenleiste.', 'Icono junto a la vista inteligente en la barra lateral.', 'Icône affichée à côté de la vue intelligente dans la barre latérale.', 'サイドバーでスマートビューの横に表示するアイコン。', '侧边栏中智能视图旁显示的图标。'),
    ('Include weekend', 'Wochenende einbeziehen', 'Incluir fin de semana', 'Inclure le week-end', '週末を含める', '包含周末'),
    ('Info journal', 'Info-Journal', 'Registro informativo', 'Journal info', '情報ジャーナル', '信息日志'),
    ('Journal diagnostics', 'Journal-Diagnose', 'Diagnóstico del registro', 'Diagnostic du journal', 'ジャーナル診断', '日志诊断'),
    ('Kanban columns', 'Kanban-Spalten', 'Columnas Kanban', 'Colonnes Kanban', 'カンバンの列', '看板列'),
    ('Kanban columns: %1', 'Kanban-Spalten: %1', 'Columnas Kanban: %1', 'Colonnes Kanban : %1', 'カンバンの列: %1', '看板列：%1'),
    ('Label (Z–A)', 'Label (Z–A)', 'Etiqueta (Z–A)', 'Étiquette (Z–A)', 'ラベル (Z–A)', '标签 (Z–A)'),
    ('Labels are already Kanban columns.', 'Labels sind bereits Kanban-Spalten.', 'Las etiquetas ya son columnas Kanban.', 'Les étiquettes sont déjà des colonnes Kanban.', 'ラベルはすでにカンバンの列です。', '标签已作为看板列。'),
    ('Labels are already swimlane rows.', 'Labels sind bereits Swimlane-Zeilen.', 'Las etiquetas ya son filas de carriles.', 'Les étiquettes sont déjà des lignes de couloirs.', 'ラベルはすでにスイムレーンの行です。', '标签已作为泳道行。'),
    ('Location (Z–A)', 'Ort (Z–A)', 'Ubicación (Z–A)', 'Lieu (Z–A)', '場所 (Z–A)', '地点 (Z–A)'),
    ('Locations', 'Orte', 'Ubicaciones', 'Lieux', '場所', '地点'),
    ('Locations come from the VTODO LOCATION field. Hidden locations will not appear in the sidebar filter list but remain on tasks.', 'Orte stammen aus dem VTODO-Feld LOCATION. Ausgeblendete Orte erscheinen nicht in der Filterliste der Seitenleiste, bleiben aber an den Aufgaben.', 'Las ubicaciones vienen del campo LOCATION de VTODO. Las ocultas no aparecen en el filtro de la barra lateral, pero siguen en las tareas.', 'Les lieux viennent du champ LOCATION de VTODO. Les lieux masqués n’apparaissent pas dans le filtre de la barre latérale mais restent sur les tâches.', '場所は VTODO の LOCATION フィールドから取得します。非表示の場所はサイドバーのフィルターに出ませんが、タスクには残ります。', '地点来自 VTODO 的 LOCATION 字段。隐藏的地点不会出现在侧边栏筛选中，但仍保留在任务上。'),
    ('Log Akonadi writes and sync state to the system journal', 'Akonadi-Schreibvorgänge und Sync-Status ins Systemjournal schreiben', 'Registrar escrituras de Akonadi y estado de sincronización en el diario del sistema', 'Journaliser les écritures Akonadi et l’état de synchro dans le journal système', 'Akonadi の書き込みと同期状態をシステムジャーナルに記録', '将 Akonadi 写入和同步状态记录到系统日志'),
    ('Log fetch, monitor, and collection details to the system journal', 'Abruf-, Monitor- und Sammlungsdetails ins Systemjournal schreiben', 'Registrar detalles de obtención, monitor y colecciones en el diario del sistema', 'Journaliser les détails de récupération, de suivi et de collections dans le journal système', '取得・監視・コレクションの詳細をシステムジャーナルに記録', '将获取、监视和集合详情记录到系统日志'),
    ('Logging', 'Protokollierung', 'Registro', 'Journalisation', 'ログ', '日志'),
    ('Maintenance', 'Wartung', 'Mantenimiento', 'Maintenance', 'メンテナンス', '维护'),
    ('Many', 'Viele', 'Muchas', 'Beaucoup', '多', '多'),
    ('Mo', 'Mo', 'lu', 'lu', '月', '一'),
    ('New location', 'Neuer Ort', 'Nueva ubicación', 'Nouveau lieu', '新しい場所', '新地点'),
    ('Next', 'Weiter', 'Siguiente', 'Suivant', '次へ', '下一个'),
    ('No events or tasks.', 'Keine Termine oder Aufgaben.', 'Sin eventos ni tareas.', 'Aucun événement ni tâche.', '予定もタスクもありません。', '没有事件或任务。'),
    ('No locations found. Locations are discovered from task LOCATION values in Akonadi, or add one below.', 'Keine Orte gefunden. Orte werden aus den LOCATION-Werten der Aufgaben in Akonadi ermittelt, oder du legst unten einen an.', 'No se encontraron ubicaciones. Se detectan de los valores LOCATION de las tareas en Akonadi, o añade una abajo.', 'Aucun lieu trouvé. Les lieux sont détectés à partir des valeurs LOCATION des tâches dans Akonadi, ou ajoutez-en un ci-dessous.', '場所が見つかりません。Akonadi のタスクの LOCATION から検出されます。下で追加することもできます。', '未找到地点。地点从 Akonadi 中任务的 LOCATION 值获取，也可在下方添加。'),
    ('No matching locations', 'Keine passenden Orte', 'Ninguna ubicación coincide', 'Aucun lieu correspondant', '一致する場所はありません', '没有匹配的地点'),
    ('No status', 'Kein Status', 'Sin estado', 'Aucun statut', '状態なし', '无状态'),
    ('Not available in the current view.', 'In der aktuellen Ansicht nicht verfügbar.', 'No disponible en la vista actual.', 'Indisponible dans la vue actuelle.', '現在のビューでは使用できません。', '当前视图中不可用。'),
    ('Only tasks matching ALL active rules are shown. Leave a filter on \\"Any\\" to disable it.', 'Es werden nur Aufgaben gezeigt, die ALLE aktiven Regeln erfüllen. Ein Filter auf „Beliebig“ ist ausgeschaltet.', 'Solo se muestran las tareas que cumplen TODAS las reglas activas. Deja un filtro en «Cualquiera» para desactivarlo.', 'Seules les tâches qui respectent TOUTES les règles actives sont affichées. Laissez un filtre sur « Tout » pour le désactiver.', '有効なすべてのルールに一致するタスクのみ表示します。「すべて」のままのフィルターは無効です。', '仅显示符合所有已启用规则的任务。筛选保持“任意”即为停用。'),
    ('Previous', 'Zurück', 'Anterior', 'Précédent', '前へ', '上一个'),
    ('Priorities are already Kanban columns.', 'Prioritäten sind bereits Kanban-Spalten.', 'Las prioridades ya son columnas Kanban.', 'Les priorités sont déjà des colonnes Kanban.', '優先度はすでにカンバンの列です。', '优先级已作为看板列。'),
    ('Priorities are already swimlane rows.', 'Prioritäten sind bereits Swimlane-Zeilen.', 'Las prioridades ya son filas de carriles.', 'Les priorités sont déjà des lignes de couloirs.', '優先度はすでにスイムレーンの行です。', '优先级已作为泳道行。'),
    ('Priority %1 (%2)', 'Priorität %1 (%2)', 'Prioridad %1 (%2)', 'Priorité %1 (%2)', '優先度 %1 (%2)', '优先级 %1（%2）'),
    ('Progress %1%', 'Fortschritt %1 %', 'Progreso %1 %', 'Progression %1 %', '進捗 %1%', '进度 %1%'),
    ('Progress is already used for Kanban columns.', 'Der Fortschritt dient bereits als Kanban-Spalten.', 'El progreso ya se usa para las columnas Kanban.', 'La progression sert déjà de colonnes Kanban.', '進捗はすでにカンバンの列に使われています。', '进度已用作看板列。'),
    ('Project (Z–A)', 'Projekt (Z–A)', 'Proyecto (Z–A)', 'Projet (Z–A)', 'プロジェクト (Z–A)', '项目 (Z–A)'),
    ('Projects are already Kanban columns.', 'Projekte sind bereits Kanban-Spalten.', 'Los proyectos ya son columnas Kanban.', 'Les projets sont déjà des colonnes Kanban.', 'プロジェクトはすでにカンバンの列です。', '项目已作为看板列。'),
    ('Projects are already plan rows.', 'Projekte sind bereits Plan-Zeilen.', 'Los proyectos ya son filas del plan.', 'Les projets sont déjà des lignes du plan.', 'プロジェクトはすでに計画の行です。', '项目已作为计划行。'),
    ('Projects are already swimlane rows.', 'Projekte sind bereits Swimlane-Zeilen.', 'Los proyectos ya son filas de carriles.', 'Les projets sont déjà des lignes de couloirs.', 'プロジェクトはすでにスイムレーンの行です。', '项目已作为泳道行。'),
    ('Remove label “%1”', 'Label „%1“ entfernen', 'Quitar etiqueta «%1»', 'Retirer l’étiquette « %1 »', 'ラベル「%1」を外す', '移除标签“%1”'),
    ('Remove label “%1” from this task?', 'Label „%1“ von dieser Aufgabe entfernen?', '¿Quitar la etiqueta «%1» de esta tarea?', 'Retirer l’étiquette « %1 » de cette tâche ?', 'このタスクからラベル「%1」を外しますか?', '从此任务移除标签“%1”？'),
    ('Remove label?', 'Label entfernen?', '¿Quitar etiqueta?', 'Retirer l’étiquette ?', 'ラベルを外しますか?', '移除标签？'),
    ('Repeat', 'Wiederholung', 'Repetir', 'Répétition', '繰り返し', '重复'),
    ('Sa', 'Sa', 'sá', 'sa', '土', '六'),
    ('Search or create label\\u2026', 'Label suchen oder anlegen…', 'Buscar o crear etiqueta…', 'Rechercher ou créer une étiquette…', 'ラベルを検索または作成…', '搜索或创建标签…'),
    ('Search or set location…', 'Ort suchen oder setzen…', 'Buscar o fijar ubicación…', 'Rechercher ou définir un lieu…', '場所を検索または設定…', '搜索或设置地点…'),
    ('Secrecy (reverse)', 'Vertraulichkeit (absteigend)', 'Confidencialidad (inversa)', 'Confidentialité (inverse)', '機密性 (逆順)', '保密性（倒序）'),
    ('Secrecy is already used for Kanban columns.', 'Die Vertraulichkeit dient bereits als Kanban-Spalten.', 'La confidencialidad ya se usa para las columnas Kanban.', 'La confidentialité sert déjà de colonnes Kanban.', '機密性はすでにカンバンの列に使われています。', '保密性已用作看板列。'),
    ('Section', 'Abschnitt', 'Sección', 'Section', 'セクション', '分区'),
    ('Set location “%1”', 'Ort „%1“ setzen', 'Fijar ubicación «%1»', 'Définir le lieu « %1 »', '場所「%1」を設定', '设置地点“%1”'),
    ('Set progress to %1', 'Fortschritt auf %1 setzen', 'Fijar progreso en %1', 'Régler la progression sur %1', '進捗を %1 に設定', '将进度设为 %1'),
    ('Set secrecy “%1”', 'Vertraulichkeit „%1“ setzen', 'Fijar confidencialidad «%1»', 'Définir la confidentialité « %1 »', '機密性「%1」を設定', '设置保密性“%1”'),
    ('Set status “%1”', 'Status „%1“ setzen', 'Fijar estado «%1»', 'Définir le statut « %1 »', '状態「%1」を設定', '设置状态“%1”'),
    ('Show only tasks from a specific project (Akonadi collection). \\"Any project\\" disables this filter.', 'Nur Aufgaben aus einem bestimmten Projekt (Akonadi-Sammlung) zeigen. „Beliebiges Projekt“ schaltet den Filter aus.', 'Mostrar solo tareas de un proyecto (colección de Akonadi). «Cualquier proyecto» desactiva este filtro.', 'N’afficher que les tâches d’un projet (collection Akonadi). « Tout projet » désactive ce filtre.', '特定のプロジェクト (Akonadi コレクション) のタスクのみ表示します。「すべてのプロジェクト」で無効になります。', '仅显示特定项目（Akonadi 集合）的任务。“任意项目”停用此筛选。'),
    ('Show only tasks with a specific label (Akonadi category). \\"Any label\\" disables this filter.', 'Nur Aufgaben mit einem bestimmten Label (Akonadi-Kategorie) zeigen. „Beliebiges Label“ schaltet den Filter aus.', 'Mostrar solo tareas con una etiqueta (categoría de Akonadi). «Cualquier etiqueta» desactiva este filtro.', 'N’afficher que les tâches portant une étiquette (catégorie Akonadi). « Toute étiquette » désactive ce filtre.', '特定のラベル (Akonadi カテゴリ) を持つタスクのみ表示します。「すべてのラベル」で無効になります。', '仅显示带有特定标签（Akonadi 类别）的任务。“任意标签”停用此筛选。'),
    ('Show this location in the sidebar filter', 'Diesen Ort im Filter der Seitenleiste zeigen', 'Mostrar esta ubicación en el filtro de la barra lateral', 'Afficher ce lieu dans le filtre de la barre latérale', 'この場所をサイドバーのフィルターに表示', '在侧边栏筛选中显示此地点'),
    ('Smart View name', 'Name der Smart View', 'Nombre de la vista inteligente', 'Nom de la vue intelligente', 'スマートビューの名前', '智能视图名称'),
    ('Star', 'Stern', 'Estrella', 'Étoile', '星', '星形'),
    ('Start', 'Beginn', 'Inicio', 'Début', '開始', '开始'),
    ('Status (reverse)', 'Status (absteigend)', 'Estado (inverso)', 'Statut (inverse)', '状態 (逆順)', '状态（倒序）'),
    ('Status is already used for Kanban columns.', 'Der Status dient bereits als Kanban-Spalten.', 'El estado ya se usa para las columnas Kanban.', 'Le statut sert déjà de colonnes Kanban.', '状態はすでにカンバンの列に使われています。', '状态已用作看板列。'),
    ('Stores KURRENT/LIST for Today-view day sections (Morning, Afternoon, Evening). Also used as the Kanban “Day section” column source.', 'Speichert KURRENT/LIST für die Tagesabschnitte der Heute-Ansicht (Morgen, Nachmittag, Abend). Dient auch als Quelle der Kanban-Spalten „Tagesabschnitt“.', 'Guarda KURRENT/LIST para las partes del día de la vista Hoy (mañana, tarde, noche). También es el origen de las columnas Kanban «Parte del día».', 'Enregistre KURRENT/LIST pour les moments de la vue Aujourd’hui (matin, après-midi, soir). Sert aussi de source aux colonnes Kanban « Moment de la journée ».', '今日ビューの時間帯 (朝・午後・夜) 用に KURRENT/LIST を保存します。カンバンの「時間帯」列のソースにもなります。', '为“今天”视图的时段（上午、下午、晚上）保存 KURRENT/LIST，也作为看板“时段”列的来源。'),
    ('Su', 'So', 'do', 'di', '日', '日'),
    ('Th', 'Do', 'ju', 'je', '木', '四'),
    ('The display name shown in the sidebar.', 'Der Name in der Seitenleiste.', 'El nombre que aparece en la barra lateral.', 'Le nom affiché dans la barre latérale.', 'サイドバーに表示する名前。', '侧边栏中显示的名称。'),
    ('The main-pane view mode used when this Smart View is active.', 'Die Darstellung des Hauptbereichs, solange diese Smart View aktiv ist.', 'El modo de vista del panel principal mientras esta vista inteligente está activa.', 'Le mode d’affichage du panneau principal quand cette vue intelligente est active.', 'このスマートビューが有効なときのメイン領域の表示モード。', '此智能视图激活时主区域使用的视图模式。'),
    ('Tu', 'Di', 'ma', 'ma', '火', '二'),
    ('Unlabeled view does not apply when Kanban uses labels as columns.', 'Die Ansicht „Ohne Label“ greift nicht, wenn Kanban Labels als Spalten nutzt.', 'La vista «Sin etiqueta» no se aplica si el Kanban usa etiquetas como columnas.', 'La vue « Sans étiquette » ne s’applique pas si le Kanban utilise les étiquettes comme colonnes.', 'カンバンがラベルを列にしている場合、「ラベルなし」ビューは適用されません。', '看板以标签为列时，“无标签”视图不适用。'),
    ('Use “%1”', '„%1“ verwenden', 'Usar «%1»', 'Utiliser « %1 »', '「%1」を使用', '使用“%1”'),
    ('Verbose journal', 'Ausführliches Journal', 'Registro detallado', 'Journal détaillé', '詳細ジャーナル', '详细日志'),
    ('View:', 'Ansicht:', 'Vista:', 'Vue :', '表示:', '视图：'),
    ('We', 'Mi', 'mi', 'me', '水', '三'),
    ('When checked, only recurring tasks are shown.', 'Wenn aktiv, werden nur wiederkehrende Aufgaben gezeigt.', 'Si está marcado, solo se muestran las tareas periódicas.', 'Si coché, seules les tâches récurrentes sont affichées.', 'オンにすると繰り返しタスクのみ表示します。', '勾选后仅显示重复任务。'),
    ('Year', 'Jahr', 'Año', 'Année', '年', '年'),
    ('task completed', 'Aufgabe erledigt', 'tarea completada', 'tâche terminée', '件完了', '个任务已完成'),
    ('task due', 'Aufgabe fällig', 'tarea con vencimiento', 'tâche à échéance', '件期限', '个任务到期'),
    ('tasks completed', 'Aufgaben erledigt', 'tareas completadas', 'tâches terminées', '件完了', '个任务已完成'),
    ('tasks due', 'Aufgaben fällig', 'tareas con vencimiento', 'tâches à échéance', '件期限', '个任务到期'),
    # Already translated in German only.
    ('Planning horizon', 'Planungshorizont', 'Horizonte de planificación', 'Horizon de planification', '計画期間', '计划范围'),
    ('Row axis', 'Zeilenachse', 'Eje de filas', 'Axe des lignes', '行の軸', '行轴'),
    ('Show undated tasks', 'Undatierte Aufgaben anzeigen', 'Mostrar tareas sin fecha', 'Afficher les tâches sans date', '日付なしのタスクを表示', '显示无日期任务'),
    ('Time grouping', 'Zeiteinteilung', 'Agrupación temporal', 'Regroupement temporel', '時間のまとまり', '时间分组'),
    ('Any label', None, 'Cualquier etiqueta', 'Toute étiquette', 'すべてのラベル', '任意标签'),
    ('Any project', None, 'Cualquier proyecto', 'Tout projet', 'すべてのプロジェクト', '任意项目'),
    ('Any section', None, 'Cualquier sección', 'Toute section', 'すべてのセクション', '任意分区'),
    ('Briefcase', None, 'Maletín', 'Mallette', 'ブリーフケース', '公文包'),
    ('Calendar', None, 'Calendario', 'Agenda', 'カレンダー', '日历'),
    ('Checkmark', None, 'Marca de verificación', 'Coche', 'チェックマーク', '勾号'),
    ('Clock', None, 'Reloj', 'Horloge', '時計', '时钟'),
    ('Contains…', None, 'Contiene…', 'Contient…', '含む…', '包含…'),
    ('Custom (manual)', None, 'Personalizado (manual)', 'Personnalisé (manuel)', 'カスタム (手動)', '自定义（手动）'),
    ('Custom column:', None, 'Columna propia:', 'Colonne personnalisée :', 'カスタム列:', '自定义列：'),
    ('Day section:', None, 'Parte del día:', 'Moment de la journée :', '時間帯:', '时段：'),
    ('Default (Priority → Due → Title)', None, 'Predeterminado (Prioridad → Vencimiento → Título)', 'Par défaut (Priorité → Échéance → Titre)', '既定 (優先度 → 期限 → タイトル)', '默认（优先级 → 截止 → 标题）'),
    ('Filter', None, 'Filtro', 'Filtre', 'フィルター', '筛选'),
    ('Filter Rules', None, 'Reglas de filtro', 'Règles de filtre', 'フィルタールール', '筛选规则'),
    ('Flag', None, 'Bandera', 'Drapeau', '旗', '旗帜'),
    ('Folder', None, 'Carpeta', 'Dossier', 'フォルダー', '文件夹'),
    ('Heart', None, 'Corazón', 'Cœur', 'ハート', '心形'),
    ('Home', None, 'Casa', 'Maison', '家', '家'),
    ('Icon:', None, 'Icono:', 'Icône :', 'アイコン:', '图标：'),
    ('KURRENT/COLUMN value…', None, 'Valor de KURRENT/COLUMN…', 'Valeur KURRENT/COLUMN…', 'KURRENT/COLUMN の値…', 'KURRENT/COLUMN 值…'),
    ('Label:', None, 'Etiqueta:', 'Étiquette :', 'ラベル:', '标签：'),
    ('Lightbulb', None, 'Bombilla', 'Ampoule', '電球', '灯泡'),
    ('Name:', None, 'Nombre:', 'Nom :', '名前:', '名称：'),
    ('Recurring tasks only', None, 'Solo tareas periódicas', 'Tâches récurrentes uniquement', '繰り返しタスクのみ', '仅重复任务'),
    ('Search text:', None, 'Texto de búsqueda:', 'Texte recherché :', '検索文字列:', '搜索文本：'),
    ('Sort by:', None, 'Ordenar por:', 'Trier par :', '並べ替え:', '排序方式：'),
    ('Tag', None, 'Etiqueta', 'Étiquette', 'タグ', '标签'),
    ('View mode:', None, 'Modo de vista:', 'Mode d’affichage :', '表示モード:', '视图模式：'),
    ('Warning', None, 'Advertencia', 'Avertissement', '警告', '警告'),
    ('Work', None, 'Trabajo', 'Travail', '仕事', '工作'),
    # Backend column labels (tasklogic kanbanColumnLabel), translated in KanbanView.
    ('Cancelled', 'Abgebrochen', 'Cancelada', 'Annulée', 'キャンセル', '已取消'),
    ('Open', 'Offen', 'Abierta', 'Ouverte', '未完了', '未完成'),
    ('Done', 'Erledigt', 'Hecha', 'Faite', '完了', '已完成'),
    ('This week', 'Diese Woche', 'Esta semana', 'Cette semaine', '今週', '本周'),
    ('Unscheduled', 'Ungeplant', 'Sin planificar', 'Non planifiée', '未計画', '未安排'),
    # Review: heatmap day list, calendar tiles and empty day.
    ('Add task for this day', 'Aufgabe für diesen Tag anlegen', 'Añadir tarea para este día', 'Ajouter une tâche pour ce jour', 'この日にタスクを追加', '为这一天添加任务'),
    ('Completed on %1', 'Erledigt am %1', 'Completadas el %1', 'Terminées le %1', '%1 に完了', '%1 完成'),
    ('Due on %1', 'Fällig am %1', 'Vencen el %1', 'À échéance le %1', '%1 が期限', '%1 到期'),
    ('Events', 'Termine', 'Eventos', 'Événements', '予定', '事件'),
    ('Events this week', 'Termine diese Woche', 'Eventos esta semana', 'Événements cette semaine', '今週の予定', '本周事件'),
    ('Next event', 'Nächster Termin', 'Próximo evento', 'Prochain événement', '次の予定', '下一个事件'),
    ('Next event · %1', 'Nächster Termin · %1', 'Próximo evento · %1', 'Prochain événement · %1', '次の予定 · %1', '下一个事件 · %1'),
    ('Nothing on this day.', 'An diesem Tag nichts.', 'Nada este día.', 'Rien ce jour-là.', 'この日は何もありません。', '这一天没有内容。'),
    ('Open in calendar', 'Im Kalender öffnen', 'Abrir en el calendario', 'Ouvrir dans l’agenda', 'カレンダーで開く', '在日历中打开'),
    ('Tasks due', 'Fällige Aufgaben', 'Tareas pendientes', 'Tâches à échéance', '期限のタスク', '到期任务'),
    ('Tasks this week', 'Aufgaben diese Woche', 'Tareas esta semana', 'Tâches cette semaine', '今週のタスク', '本周任务'),
]

_LANGS = ["de", "es", "fr", "ja", "zh_CN"]
REVIEW = {lang: {} for lang in _LANGS}
for _row in _ROWS:
    for _i, _lang in enumerate(_LANGS):
        if _row[_i + 1] is not None:
            REVIEW[_lang][_row[0]] = _row[_i + 1]
