"""Remaining 1.0 gap strings — merged by _merge_catalog.py."""

GAPS2 = {
    "de": {
        "%1% complete": "%1 % erledigt",
        "+1 day": "+1 Tag",
        "Any due date": "Beliebiges Fälligkeitsdatum",
        "Any priority": "Beliebige Priorität",
        "Any status": "Beliebiger Status",
        "Both": "Beides",
        "Busy days:": "Volle Tage:",
        "Cancelled": "Abgebrochen",
        "Clear cell filter": "Zellenfilter aufheben",
        "Copy UIDs": "UIDs kopieren",
        "Day": "Tag",
        "Dismiss": "Schließen",
        "Duplicate built-in view…": "Built-in-View duplizieren …",
        "Edit Smart View": "Smart View bearbeiten",
        "Icon name (Plasma icon)": "Icon-Name (Plasma-Icon)",
        "KURRENT/COLUMN": "KURRENT/COLUMN",
        "KURRENT/COLUMN only": "Nur KURRENT/COLUMN",
        "KURRENT/LIST (day section)": "KURRENT/LIST (Tagesabschnitt)",
        "Kanban writes": "Kanban schreibt",
        "Lane axis (rows)": "Spurachse (Zeilen)",
        "Month": "Monat",
        "Move to project": "In Projekt verschieben",
        "Name": "Name",
        "No date": "Kein Datum",
        "Open": "Offen",
        "Open map": "Karte öffnen",
        "Parent task": "Übergeordnete Aufgabe",
        "Recurring only": "Nur wiederkehrend",
        "Reload": "Neu laden",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "Gespeicherte Filter erscheinen in der Seitenleiste. Jeder kann Filterregeln und einen Standard-Hauptansichtsmodus setzen.",
        "Set priority": "Priorität setzen",
        "Show %1 tasks": "%1 Aufgaben anzeigen",
        "Sort override (e.g. priority,due,title)": "Sortierung überschreiben (z. B. priority,due,title)",
        "Standard VTODO fields": "Standard-VTODO-Felder",
        "Text contains": "Text enthält",
        "This task was changed on the server. Reload to discard your edit.":
            "Diese Aufgabe wurde auf dem Server geändert. Neu laden, um deine Änderung zu verwerfen.",
        "This week": "Diese Woche",
        "Time axis (columns)": "Zeitachse (Spalten)",
        "Week": "Woche",
        "tasks": "Aufgaben",
    },
    "es": {
        "%1% complete": "%1 % completado",
        "+1 day": "+1 día",
        "Any due date": "Cualquier fecha de vencimiento",
        "Any priority": "Cualquier prioridad",
        "Any status": "Cualquier estado",
        "Both": "Ambos",
        "Busy days:": "Días ocupados:",
        "Cancelled": "Cancelado",
        "Clear cell filter": "Quitar filtro de celda",
        "Copy UIDs": "Copiar UIDs",
        "Day": "Día",
        "Dismiss": "Descartar",
        "Duplicate built-in view…": "Duplicar vista integrada…",
        "Edit Smart View": "Editar vista inteligente",
        "Icon name (Plasma icon)": "Nombre del icono (icono de Plasma)",
        "KURRENT/COLUMN": "KURRENT/COLUMN",
        "KURRENT/COLUMN only": "Solo KURRENT/COLUMN",
        "KURRENT/LIST (day section)": "KURRENT/LIST (sección del día)",
        "Kanban writes": "Kanban escribe",
        "Lane axis (rows)": "Eje de carriles (filas)",
        "Month": "Mes",
        "Move to project": "Mover al proyecto",
        "Name": "Nombre",
        "No date": "Sin fecha",
        "Open": "Abierto",
        "Open map": "Abrir mapa",
        "Parent task": "Tarea principal",
        "Recurring only": "Solo recurrentes",
        "Reload": "Recargar",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "Los filtros guardados aparecen en la barra lateral. Cada uno puede definir reglas y un modo principal predeterminado.",
        "Set priority": "Establecer prioridad",
        "Show %1 tasks": "Mostrar %1 tareas",
        "Sort override (e.g. priority,due,title)": "Orden personalizado (p. ej. priority,due,title)",
        "Standard VTODO fields": "Campos VTODO estándar",
        "Text contains": "El texto contiene",
        "This task was changed on the server. Reload to discard your edit.":
            "Esta tarea cambió en el servidor. Recarga para descartar tu edición.",
        "This week": "Esta semana",
        "Time axis (columns)": "Eje temporal (columnas)",
        "Week": "Semana",
        "tasks": "tareas",
    },
    "fr": {
        "%1% complete": "%1 % terminé",
        "+1 day": "+1 jour",
        "Any due date": "N'importe quelle échéance",
        "Any priority": "N'importe quelle priorité",
        "Any status": "N'importe quel statut",
        "Both": "Les deux",
        "Busy days:": "Jours chargés :",
        "Cancelled": "Annulé",
        "Clear cell filter": "Effacer le filtre de cellule",
        "Copy UIDs": "Copier les UIDs",
        "Day": "Jour",
        "Dismiss": "Ignorer",
        "Duplicate built-in view…": "Dupliquer une vue intégrée…",
        "Edit Smart View": "Modifier la vue intelligente",
        "Icon name (Plasma icon)": "Nom de l'icône (icône Plasma)",
        "KURRENT/COLUMN": "KURRENT/COLUMN",
        "KURRENT/COLUMN only": "KURRENT/COLUMN uniquement",
        "KURRENT/LIST (day section)": "KURRENT/LIST (section du jour)",
        "Kanban writes": "Écriture Kanban",
        "Lane axis (rows)": "Axe des couloirs (lignes)",
        "Month": "Mois",
        "Move to project": "Déplacer vers le projet",
        "Name": "Nom",
        "No date": "Sans date",
        "Open": "Ouvert",
        "Open map": "Ouvrir la carte",
        "Parent task": "Tâche parente",
        "Recurring only": "Récurrentes seulement",
        "Reload": "Recharger",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "Les filtres enregistrés apparaissent dans la barre latérale. Chacun peut définir des règles et un mode principal par défaut.",
        "Set priority": "Définir la priorité",
        "Show %1 tasks": "Afficher %1 tâches",
        "Sort override (e.g. priority,due,title)": "Tri personnalisé (p. ex. priority,due,title)",
        "Standard VTODO fields": "Champs VTODO standard",
        "Text contains": "Le texte contient",
        "This task was changed on the server. Reload to discard your edit.":
            "Cette tâche a été modifiée sur le serveur. Rechargez pour annuler votre modification.",
        "This week": "Cette semaine",
        "Time axis (columns)": "Axe temporel (colonnes)",
        "Week": "Semaine",
        "tasks": "tâches",
    },
    "ja": {
        "%1% complete": "%1% 完了",
        "+1 day": "+1 日",
        "Any due date": "期限日を問わない",
        "Any priority": "優先度を問わない",
        "Any status": "状態を問わない",
        "Both": "両方",
        "Busy days:": "予定のある日:",
        "Cancelled": "キャンセル",
        "Clear cell filter": "セルフィルターを解除",
        "Copy UIDs": "UID をコピー",
        "Day": "日",
        "Dismiss": "閉じる",
        "Duplicate built-in view…": "組み込みビューを複製…",
        "Edit Smart View": "スマートビューを編集",
        "Icon name (Plasma icon)": "アイコン名 (Plasma アイコン)",
        "KURRENT/COLUMN": "KURRENT/COLUMN",
        "KURRENT/COLUMN only": "KURRENT/COLUMN のみ",
        "KURRENT/LIST (day section)": "KURRENT/LIST (時間帯)",
        "Kanban writes": "カンバンの書き込み",
        "Lane axis (rows)": "レーン軸 (行)",
        "Month": "月",
        "Move to project": "プロジェクトへ移動",
        "Name": "名前",
        "No date": "日付なし",
        "Open": "未完了",
        "Open map": "地図を開く",
        "Parent task": "親タスク",
        "Recurring only": "繰り返しのみ",
        "Reload": "再読み込み",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "保存したフィルターはサイドバーに表示されます。各ビューでルールと既定のメインモードを設定できます。",
        "Set priority": "優先度を設定",
        "Show %1 tasks": "%1 件のタスクを表示",
        "Sort override (e.g. priority,due,title)": "並べ替えの上書き (例: priority,due,title)",
        "Standard VTODO fields": "標準 VTODO フィールド",
        "Text contains": "テキストを含む",
        "This task was changed on the server. Reload to discard your edit.":
            "サーバー側でこのタスクが変更されました。再読み込みすると編集内容は破棄されます。",
        "This week": "今週",
        "Time axis (columns)": "時間軸 (列)",
        "Week": "週",
        "tasks": "タスク",
    },
    "zh_CN": {
        "%1% complete": "已完成 %1%",
        "+1 day": "+1 天",
        "Any due date": "任意截止日期",
        "Any priority": "任意优先级",
        "Any status": "任意状态",
        "Both": "两者",
        "Busy days:": "忙碌日：",
        "Cancelled": "已取消",
        "Clear cell filter": "清除单元格筛选",
        "Copy UIDs": "复制 UID",
        "Day": "日",
        "Dismiss": "关闭",
        "Duplicate built-in view…": "复制内置视图…",
        "Edit Smart View": "编辑智能视图",
        "Icon name (Plasma icon)": "图标名称（Plasma 图标）",
        "KURRENT/COLUMN": "KURRENT/COLUMN",
        "KURRENT/COLUMN only": "仅 KURRENT/COLUMN",
        "KURRENT/LIST (day section)": "KURRENT/LIST（时段）",
        "Kanban writes": "看板写入",
        "Lane axis (rows)": "泳道轴（行）",
        "Month": "月",
        "Move to project": "移动到项目",
        "Name": "名称",
        "No date": "无日期",
        "Open": "未完成",
        "Open map": "打开地图",
        "Parent task": "父任务",
        "Recurring only": "仅重复任务",
        "Reload": "重新加载",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "已保存的筛选器显示在侧边栏。每个筛选器可设置规则和默认主视图模式。",
        "Set priority": "设置优先级",
        "Show %1 tasks": "显示 %1 个任务",
        "Sort override (e.g. priority,due,title)": "排序覆盖（如 priority,due,title）",
        "Standard VTODO fields": "标准 VTODO 字段",
        "Text contains": "文本包含",
        "This task was changed on the server. Reload to discard your edit.":
            "此任务已在服务器上更改。重新加载将放弃你的编辑。",
        "This week": "本周",
        "Time axis (columns)": "时间轴（列）",
        "Week": "周",
        "tasks": "任务",
    },
}
