"""1.0 UI strings — merged by _merge_catalog.py into extra_translations."""

ADDON = {
        "de": {
        "Add": "Hinzufügen",
        "Add Smart View": "Smart View hinzufügen",
        "Akonadi and plugin diagnostics": "Akonadi- und Plugin-Diagnose",
        "Afternoon": "Nachmittag",
        "Any due date": "Beliebiges Fälligkeitsdatum",
        "Any label": "Beliebiges Label",
        "Any priority": "Beliebige Priorität",
        "Any project": "Beliebiges Projekt",
        "Any section": "Beliebiger Abschnitt",
        "Any status": "Beliebiger Status",
        "Appearance": "Erscheinungsbild",
        "Assignees:": "Zugewiesen:",
        "Briefcase": "Aktentasche",
        "Calendar": "Kalender",
        "Calendar + tasks": "Kalender + Aufgaben",
        "Checkmark": "Häkchen",
        "Clear selection": "Auswahl aufheben",
        "Clock": "Uhr",
        "Complete": "Erledigen",
        "Completion": "Erledigt",
        "Completions": "Erledigungen",
        "Contains…": "Enthält…",
        "Copy": "Kopieren",
        "Copy debug bundle": "Debug-Paket kopieren",
        "Custom column (KCURRENT/COLUMN)": "Eigene Spalte (KCURRENT/COLUMN)",
        "Custom (manual)": "Benutzerdefiniert (manuell)",
        "Day agenda": "Tagesagenda",
        "Day section": "Tagesabschnitt",
        "Debug info": "Debug-Info",
        "Default column source": "Standard-Spaltenquelle",
        "Default (Priority → Due → Title)": "Standard (Priorität → Fälligkeit → Titel)",
        "Diagnostics": "Diagnose",
        "Due date": "Fälligkeit",
        "Due date (latest first)": "Fälligkeit (späteste zuerst)",
        "Due date buckets": "Fälligkeits-Buckets",
        "Due dates": "Fälligkeiten",
        "Duplicate built-in view…": "Standard-Ansicht duplizieren …",
        "Edit Smart View": "Smart View bearbeiten",
        "Enable multi-select (Ctrl+click) and bulk actions":
            "Mehrfachauswahl (Strg+Klick) und Sammelaktionen aktivieren",
        "Evening": "Abend",
        "Filter": "Filter",
        "Filter Rules": "Filterregeln",
        "Flag": "Flagge",
        "Folder": "Ordner",
        "Heart": "Herz",
        "Heatmap": "Heatmap",
        "Home": "Zuhause",
        "Icon:": "Symbol:",
        "Inbox": "Posteingang",
        "KCURRENT/COLUMN only": "Nur KCURRENT/COLUMN",
        "KCURRENT/COLUMN value…": "KCURRENT/COLUMN-Wert…",
        "Kanban": "Kanban",
        "Label": "Label",
        "Label:": "Label:",
        "Lightbulb": "Glühbirne",
        "List": "Liste",
        "Mode:": "Modus:",
        "Morning": "Morgen",
        "Name:": "Name:",
        "New Smart View": "Neue Smart View",
        "No busy events for this day.": "Keine busy-Termine an diesem Tag.",
        "No dated open tasks in this view.": "Keine datierten offenen Aufgaben in dieser Ansicht.",
        "Not loaded": "Nicht geladen",
        "Offline": "Offline",
        "Online": "Online",
        "Open tasks by project and week": "Offene Aufgaben nach Projekt und Woche",
        "Pending jobs": "Ausstehende Jobs",
        "Plugin version": "Plugin-Version",
        "Priority": "Priorität",
        "Priority:": "Priorität:",
        "Project": "Projekt",
        "Project plan": "Projektplan",
        "Project:": "Projekt:",
        "Progress %": "Fortschritt %",
        "Progress % (high first)": "Fortschritt % (höchste zuerst)",
        "Release": "Release",
        "Recurring tasks only": "Nur wiederkehrende Aufgaben",
        "Saved filters appear in the sidebar. Each can set filter rules and a default main-pane mode.":
            "Gespeicherte Filter erscheinen in der Seitenleiste. Jeder kann Filterregeln und einen Standard-Hauptansichtsmodus setzen.",
        "Search": "Suche",
        "Search text:": "Suchtext:",
        "Selection": "Auswahl",
        "Set KURRENT_SMOKE=1 and check ~/.cache/kurrent-smoke/ for logs.":
            "KURRENT_SMOKE=1 setzen und ~/.cache/kurrent-smoke/ auf Logs prüfen.",
        "Smart Views": "Smart Views",
        "Smoke test": "Smoke-Test",
        "Sort by:": "Sortieren nach:",
        "Start date": "Startdatum",
        "Status": "Status",
        "Status:": "Status:",
        "Swimlanes": "Swimlanes",
        "Syncing…": "Synchronisiere …",
        "Tag": "Tag",
        "Tasks due this day": "An diesem Tag fällige Aufgaben",
        "Title A–Z": "Titel A–Z",
        "Title Z–A": "Titel Z–A",
        "Unscheduled": "Ungeplant",
        "View mode": "Ansichtsmodus",
        "View mode: %1": "Ansichtsmodus: %1",
        "View mode:": "Ansichtsmodus:",
        "Warning": "Warnung",
        "Work": "Arbeit",
        "Day section:": "Tagesabschnitt:",
        "Custom column:": "Eigene Spalte:",
    },
   
        "Open full editor": "Vollständigen Editor öffnen",
 "es": {
        "Add": "Añadir",
        "Add Smart View": "Añadir vista inteligente",
        "Akonadi and plugin diagnostics": "Diagnóstico de Akonadi y del complemento",
        "Assignees:": "Asignados:",
        "Calendar + tasks": "Calendario + tareas",
        "Clear selection": "Borrar selección",
        "Complete": "Completar",
        "Completion": "Completadas",
        "Completions": "Completadas",
        "Copy": "Copiar",
        "Copy debug bundle": "Copiar paquete de depuración",
        "Custom column (KURRENT/COLUMN)": "Columna personalizada (KURRENT/COLUMN)",
        "Day agenda": "Agenda del día",
        "Day section": "Sección del día",
        "Debug info": "Info de depuración",
        "Default column source": "Origen de columnas predeterminado",
        "Diagnostics": "Diagnóstico",
        "Due date buckets": "Grupos de vencimiento",
        "Due dates": "Fechas de vencimiento",
        "Enable multi-select (Ctrl+click) and bulk actions":
            "Activar selección múltiple (Ctrl+clic) y acciones en lote",
        "Heatmap": "Mapa de calor",
        "Kanban": "Kanban",
        "Label": "Etiqueta",
        "List": "Lista",
        "Mode:": "Modo:",
        "New Smart View": "Nueva vista inteligente",
        "No busy events for this day.": "No hay eventos ocupados este día.",
        "No dated open tasks in this view.": "No hay tareas abiertas con fecha en esta vista.",
        "Not loaded": "No cargado",
        "Offline": "Desconectado",
        "Online": "En línea",
        "Open tasks by project and week": "Tareas abiertas por proyecto y semana",
        "Pending jobs": "Trabajos pendientes",
        "Plugin version": "Versión del complemento",
        "Project": "Proyecto",
        "Project plan": "Plan de proyecto",
        "Release": "Versión",
        "Saved filters appear in the sidebar. Each can set a default main-pane mode.":
            "Los filtros guardados aparecen en la barra lateral. Cada uno puede fijar un modo de panel principal.",
        "Selection": "Selección",
        "Set KURRENT_SMOKE=1 and check ~/.cache/kurrent-smoke/ for logs.":
            "Establece KURRENT_SMOKE=1 y revisa ~/.cache/kurrent-smoke/ para los registros.",
        "Smart Views": "Vistas inteligentes",
        "Smoke test": "Prueba de humo",
        "Swimlanes": "Carriles",
        "Syncing…": "Sincronizando…",
        "Tasks due this day": "Tareas que vencen este día",
        "Unscheduled": "Sin programar",
        "View mode": "Modo de vista",
        "View mode: %1": "Modo de vista: %1",
    },
    "fr": {
        "Add": "Ajouter",
        "Add Smart View": "Ajouter une vue intelligente",
        "Akonadi and plugin diagnostics": "Diagnostics Akonadi et greffon",
        "Assignees:": "Assignés :",
        "Calendar + tasks": "Calendrier + tâches",
        "Clear selection": "Effacer la sélection",
        "Complete": "Terminer",
        "Completion": "Terminées",
        "Completions": "Achèvements",
        "Copy": "Copier",
        "Copy debug bundle": "Copier le paquet de débogage",
        "Custom column (KURRENT/COLUMN)": "Colonne personnalisée (KURRENT/COLUMN)",
        "Day agenda": "Agenda du jour",
        "Day section": "Section du jour",
        "Debug info": "Infos de débogage",
        "Default column source": "Source de colonnes par défaut",
        "Diagnostics": "Diagnostics",
        "Due date buckets": "Tranches d’échéance",
        "Due dates": "Dates d’échéance",
        "Enable multi-select (Ctrl+click) and bulk actions":
            "Activer la sélection multiple (Ctrl+clic) et les actions groupées",
        "Heatmap": "Carte thermique",
        "Kanban": "Kanban",
        "Label": "Étiquette",
        "List": "Liste",
        "Mode:": "Mode :",
        "New Smart View": "Nouvelle vue intelligente",
        "No busy events for this day.": "Aucun événement occupé ce jour.",
        "No dated open tasks in this view.": "Aucune tâche ouverte datée dans cette vue.",
        "Not loaded": "Non chargé",
        "Offline": "Hors ligne",
        "Online": "En ligne",
        "Open tasks by project and week": "Tâches ouvertes par projet et semaine",
        "Pending jobs": "Travaux en attente",
        "Plugin version": "Version du greffon",
        "Project": "Projet",
        "Project plan": "Plan de projet",
        "Release": "Version",
        "Saved filters appear in the sidebar. Each can set a default main-pane mode.":
            "Les filtres enregistrés apparaissent dans la barre latérale. Chacun peut définir un mode de volet principal.",
        "Selection": "Sélection",
        "Set KURRENT_SMOKE=1 and check ~/.cache/kurrent-smoke/ for logs.":
            "Définir KURRENT_SMOKE=1 et consulter ~/.cache/kurrent-smoke/ pour les journaux.",
        "Smart Views": "Vues intelligentes",
        "Smoke test": "Test fumée",
        "Swimlanes": "Couloirs",
        "Syncing…": "Synchronisation…",
        "Tasks due this day": "Tâches dues ce jour",
        "Unscheduled": "Non planifiées",
        "View mode": "Mode d’affichage",
        "View mode: %1": "Mode d’affichage : %1",
    },
    "ja": {
        "Add": "追加",
        "Add Smart View": "スマートビューを追加",
        "Akonadi and plugin diagnostics": "Akonadi とプラグインの診断",
        "Assignees:": "担当者:",
        "Calendar + tasks": "カレンダー + タスク",
        "Clear selection": "選択を解除",
        "Complete": "完了",
        "Completion": "完了",
        "Completions": "完了数",
        "Copy": "コピー",
        "Copy debug bundle": "デバッグ情報をコピー",
        "Custom column (KURRENT/COLUMN)": "カスタム列 (KURRENT/COLUMN)",
        "Day agenda": "日のアジェンダ",
        "Day section": "日の区分",
        "Debug info": "デバッグ情報",
        "Default column source": "デフォルトの列ソース",
        "Diagnostics": "診断",
        "Due date buckets": "期限バケット",
        "Due dates": "期限",
        "Enable multi-select (Ctrl+click) and bulk actions":
            "複数選択 (Ctrl+クリック) と一括操作を有効化",
        "Heatmap": "ヒートマップ",
        "Kanban": "カンバン",
        "Label": "ラベル",
        "List": "リスト",
        "Mode:": "モード:",
        "New Smart View": "新しいスマートビュー",
        "No busy events for this day.": "この日の予定はありません。",
        "No dated open tasks in this view.": "このビューに日付付きの未完了タスクはありません。",
        "Not loaded": "未読み込み",
        "Offline": "オフライン",
        "Online": "オンライン",
        "Open tasks by project and week": "プロジェクトと週ごとの未完了タスク",
        "Pending jobs": "保留中のジョブ",
        "Plugin version": "プラグインバージョン",
        "Project": "プロジェクト",
        "Project plan": "プロジェクト計画",
        "Release": "リリース",
        "Saved filters appear in the sidebar. Each can set a default main-pane mode.":
            "保存したフィルターはサイドバーに表示されます。各ビューでデフォルトのメインペインモードを設定できます。",
        "Selection": "選択",
        "Set KURRENT_SMOKE=1 and check ~/.cache/kurrent-smoke/ for logs.":
            "KURRENT_SMOKE=1 を設定し、ログは ~/.cache/kurrent-smoke/ を確認してください。",
        "Smart Views": "スマートビュー",
        "Smoke test": "スモークテスト",
        "Swimlanes": "スイムレーン",
        "Syncing…": "同期中…",
        "Tasks due this day": "この日が期限のタスク",
        "Unscheduled": "未スケジュール",
        "View mode": "表示モード",
        "View mode: %1": "表示モード: %1",
    },
    "zh_CN": {
        "Add": "添加",
        "Add Smart View": "添加智能视图",
        "Akonadi and plugin diagnostics": "Akonadi 与插件诊断",
        "Assignees:": "负责人：",
        "Calendar + tasks": "日历 + 任务",
        "Clear selection": "清除选择",
        "Complete": "完成",
        "Completion": "完成",
        "Completions": "完成数",
        "Copy": "复制",
        "Copy debug bundle": "复制调试信息",
        "Custom column (KURRENT/COLUMN)": "自定义列 (KURRENT/COLUMN)",
        "Day agenda": "日议程",
        "Day section": "日分区",
        "Debug info": "调试信息",
        "Default column source": "默认列来源",
        "Diagnostics": "诊断",
        "Due date buckets": "截止日期分组",
        "Due dates": "截止日期",
        "Enable multi-select (Ctrl+click) and bulk actions":
            "启用多选 (Ctrl+点击) 和批量操作",
        "Heatmap": "热力图",
        "Kanban": "看板",
        "Label": "标签",
        "List": "列表",
        "Mode:": "模式：",
        "New Smart View": "新建智能视图",
        "No busy events for this day.": "今天没有忙碌日程。",
        "No dated open tasks in this view.": "此视图中没有带日期的未完成任务。",
        "Not loaded": "未加载",
        "Offline": "离线",
        "Online": "在线",
        "Open tasks by project and week": "按项目和周显示的未完成任务",
        "Pending jobs": "待处理作业",
        "Plugin version": "插件版本",
        "Project": "项目",
        "Project plan": "项目计划",
        "Release": "发布",
        "Saved filters appear in the sidebar. Each can set a default main-pane mode.":
            "已保存的筛选器显示在侧栏。每个可设置默认主面板模式。",
        "Selection": "选择",
        "Set KURRENT_SMOKE=1 and check ~/.cache/kurrent-smoke/ for logs.":
            "设置 KURRENT_SMOKE=1 并查看 ~/.cache/kurrent-smoke/ 中的日志。",
        "Smart Views": "智能视图",
        "Smoke test": "冒烟测试",
        "Swimlanes": "泳道",
        "Syncing…": "同步中…",
        "Tasks due this day": "当天到期的任务",
        "Unscheduled": "未安排",
        "View mode": "视图模式",
        "View mode: %1": "视图模式：%1",
    },
}
