"""Swimlanes / Project plan polish (matrix views) — merged by _merge_catalog.py."""

MATRIX = {
    "de": {
        "No parent": "Kein Parent",
        "%1 completed": "%1 erledigt",
        "%1 high priority": "%1 mit hoher Priorität",
        "%1 overdue": "%1 überfällig",
        "Automatic": "Automatisch",
        "Back to the matrix": "Zurück zur Matrix",
        "Clear filter": "Filter entfernen",
        "Columns": "Spalten",
        "Give tasks a due or start date to see them planned by project and period.":
            "Gib Aufgaben ein Fälligkeits- oder Startdatum, um sie nach Projekt und Zeitraum geplant zu sehen.",
        "Jump to current period": "Zum aktuellen Zeitraum springen",
        "Later": "Später",
        "Look ahead": "Vorausschau",
        "No label": "Kein Label",
        "Number of tasks per period": "Anzahl der Aufgaben pro Zeitraum",
        "Periods shown ahead of the current one. 0 = automatic (14 days, 8 weeks or 6 months). Later tasks are collected in one column.":
            "Anzahl der Zeiträume nach dem aktuellen. 0 = automatisch (14 Tage, 8 Wochen oder 6 Monate). Spätere Aufgaben werden in einer Spalte gesammelt.",
        "Project plan options": "Projektplan-Optionen",
        "Rows": "Zeilen",
        "Swimlane horizon": "Swimlane-Vorausschau",
        "Swimlane options": "Swimlane-Optionen",
        "Tasks appear here by row and period once they match the current view.":
            "Aufgaben erscheinen hier nach Zeile und Zeitraum, sobald sie zur aktuellen Ansicht passen.",
        "Week %1": "KW %1",
        "high priority": "hohe Priorität",
        "overdue": "überfällig",
    },
    "es": {
        "No parent": "Sin tarea padre",
        "%1 completed": "%1 completadas",
        "%1 high priority": "%1 de prioridad alta",
        "%1 overdue": "%1 vencidas",
        "Automatic": "Automático",
        "Back to the matrix": "Volver a la matriz",
        "Clear filter": "Quitar filtro",
        "Columns": "Columnas",
        "Give tasks a due or start date to see them planned by project and period.":
            "Asigna una fecha de vencimiento o de inicio a las tareas para verlas planificadas por proyecto y período.",
        "Jump to current period": "Ir al período actual",
        "Later": "Más adelante",
        "Look ahead": "Horizonte",
        "No label": "Sin etiqueta",
        "Number of tasks per period": "Número de tareas por período",
        "Periods shown ahead of the current one. 0 = automatic (14 days, 8 weeks or 6 months). Later tasks are collected in one column.":
            "Períodos que se muestran después del actual. 0 = automático (14 días, 8 semanas o 6 meses). Las tareas posteriores se agrupan en una columna.",
        "Project plan options": "Opciones del plan de proyecto",
        "Rows": "Filas",
        "Swimlane horizon": "Horizonte de carriles",
        "Swimlane options": "Opciones de carriles",
        "Tasks appear here by row and period once they match the current view.":
            "Las tareas aparecerán aquí por fila y período cuando coincidan con la vista actual.",
        "Week %1": "Semana %1",
        "high priority": "prioridad alta",
        "overdue": "vencidas",
    },
    "fr": {
        "No parent": "Sans tâche parente",
        "%1 completed": "%1 terminées",
        "%1 high priority": "%1 de priorité haute",
        "%1 overdue": "%1 en retard",
        "Automatic": "Automatique",
        "Back to the matrix": "Retour à la matrice",
        "Clear filter": "Effacer le filtre",
        "Columns": "Colonnes",
        "Give tasks a due or start date to see them planned by project and period.":
            "Donnez une date d’échéance ou de début aux tâches pour les voir planifiées par projet et par période.",
        "Jump to current period": "Aller à la période actuelle",
        "Later": "Plus tard",
        "Look ahead": "Horizon",
        "No label": "Sans étiquette",
        "Number of tasks per period": "Nombre de tâches par période",
        "Periods shown ahead of the current one. 0 = automatic (14 days, 8 weeks or 6 months). Later tasks are collected in one column.":
            "Périodes affichées après la période actuelle. 0 = automatique (14 jours, 8 semaines ou 6 mois). Les tâches plus tardives sont regroupées dans une colonne.",
        "Project plan options": "Options du plan de projet",
        "Rows": "Lignes",
        "Swimlane horizon": "Horizon des couloirs",
        "Swimlane options": "Options des couloirs",
        "Tasks appear here by row and period once they match the current view.":
            "Les tâches apparaîtront ici par ligne et par période dès qu’elles correspondent à la vue actuelle.",
        "Week %1": "Semaine %1",
        "high priority": "priorité haute",
        "overdue": "en retard",
    },
    "ja": {
        "No parent": "親タスクなし",
        "%1 completed": "%1 件完了",
        "%1 high priority": "優先度高 %1 件",
        "%1 overdue": "期限超過 %1 件",
        "Automatic": "自動",
        "Back to the matrix": "マトリクスに戻る",
        "Clear filter": "フィルターを解除",
        "Columns": "列",
        "Give tasks a due or start date to see them planned by project and period.":
            "期限日または開始日を設定すると、プロジェクトと期間ごとの計画に表示されます。",
        "Jump to current period": "現在の期間へ移動",
        "Later": "それ以降",
        "Look ahead": "先読み期間",
        "No label": "ラベルなし",
        "Number of tasks per period": "期間ごとのタスク数",
        "Periods shown ahead of the current one. 0 = automatic (14 days, 8 weeks or 6 months). Later tasks are collected in one column.":
            "現在の期間より先に表示する期間数。0 = 自動（14日、8週間、または6か月）。それ以降のタスクは1つの列にまとめられます。",
        "Project plan options": "プロジェクト計画のオプション",
        "Rows": "行",
        "Swimlane horizon": "スイムレーンの先読み期間",
        "Swimlane options": "スイムレーンのオプション",
        "Tasks appear here by row and period once they match the current view.":
            "現在のビューに一致するタスクが、行と期間ごとにここに表示されます。",
        "Week %1": "第%1週",
        "high priority": "優先度高",
        "overdue": "期限超過",
    },
    "zh_CN": {
        "No parent": "无父任务",
        "%1 completed": "%1 个已完成",
        "%1 high priority": "%1 个高优先级",
        "%1 overdue": "%1 个已逾期",
        "Automatic": "自动",
        "Back to the matrix": "返回矩阵",
        "Clear filter": "清除筛选",
        "Columns": "列",
        "Give tasks a due or start date to see them planned by project and period.":
            "为任务设置截止或开始日期，即可按项目和时间段查看计划。",
        "Jump to current period": "跳转到当前时间段",
        "Later": "更晚",
        "Look ahead": "展望范围",
        "No label": "无标签",
        "Number of tasks per period": "每个时间段的任务数",
        "Periods shown ahead of the current one. 0 = automatic (14 days, 8 weeks or 6 months). Later tasks are collected in one column.":
            "在当前时间段之后显示的时间段数量。0 = 自动（14 天、8 周或 6 个月）。更晚的任务会集中在一列中。",
        "Project plan options": "项目计划选项",
        "Rows": "行",
        "Swimlane horizon": "泳道展望范围",
        "Swimlane options": "泳道选项",
        "Tasks appear here by row and period once they match the current view.":
            "符合当前视图的任务将按行和时间段显示在这里。",
        "Week %1": "第 %1 周",
        "high priority": "高优先级",
        "overdue": "已逾期",
    },
}
