"""Gaps found in the redesign review (settings pages, smart views, heatmap, calendar) — merged by _merge_catalog.py.

Each row: msgid (as written in QML, escapes kept), de, es, fr, ja, zh_CN. None = keep the existing translation.
"""

_ROWS = [
    ('%1 %2 on %3', '%1 %2 am %3', '%1 %2 el %3', '%1 %2 le %3', '%3: %1 %2', '%3：%1 %2'),
    ('0 = show all time periods', '0 = alle Zeiträume anzeigen', '0 = mostrar todos los periodos', '0 = afficher toutes les périodes', '0 = すべての期間を表示', '0 = 显示所有时间段'),
    ('0–25%', '0–25 %', '0–25 %', '0–25 %', '0–25%', '0–25%'),
    ('26–50%', '26–50 %', '26–50 %', '26–50 %', '26–50%', '26–50%'),
    ('51–75%', '51–75 %', '51–75 %', '51–75 %', '51–75%', '51–75%'),
    ('76–100%', '76–100 %', '76–100 %', '76–100 %', '76–100%', '76–100%'),
    ('Add location', 'Ort hinzufügen', 'Añadir ubicación', 'Ajouter un lieu', '場所を追加', '添加地点'),
    ('Agenda', 'Agenda', 'Agenda', 'Agenda', 'アジェンダ', '日程'),
    ('Assignees', 'Zuständige', 'Asignados', 'Responsables', '担当者', '负责人'),
    ('Back', 'Zurück', 'Atrás', 'Retour', '戻る', '返回'),
    ('Both use com.github.shrippen.kurrent.akonadi. Info covers writes and sync (Qt Info). Verbose adds fetch/monitor lines (Qt Debug).',
     'Beide nutzen com.github.shrippen.kurrent.akonadi. Info umfasst Schreibvorgänge und Sync (Qt Info). Ausführlich ergänzt Abruf- und Monitorzeilen (Qt Debug).',
     'Ambos usan com.github.shrippen.kurrent.akonadi. Info cubre escrituras y sincronización (Qt Info). Detallado añade líneas de obtención y monitor (Qt Debug).',
     'Les deux utilisent com.github.shrippen.kurrent.akonadi. Info couvre les écritures et la synchro (Qt Info). Détaillé ajoute les lignes de récupération et de suivi (Qt Debug).',
     'どちらも com.github.shrippen.kurrent.akonadi を使用します。情報は書き込みと同期 (Qt Info)、詳細は取得・監視の行 (Qt Debug) を追加します。',
     '两者均使用 com.github.shrippen.kurrent.akonadi。信息包含写入和同步 (Qt Info)，详细另含获取/监视日志 (Qt Debug)。'),
    ('Category', 'Kategorie', 'Categoría', 'Catégorie', 'カテゴリ', '类别'),
    ('Choose calendars', 'Kalender wählen', 'Elegir calendarios', 'Choisir les agendas', 'カレンダーを選択', '选择日历'),
    ('Choose how this Smart View looks and sorts tasks.', 'Lege fest, wie diese Smart View aussieht und Aufgaben sortiert.', 'Elige cómo se ve esta vista inteligente y cómo ordena las tareas.', 'Choisissez l’apparence de cette vue intelligente et le tri des tâches.', 'このスマートビューの表示と並べ替えを選択します。', '选择此智能视图的外观和任务排序方式。'),
    ('Clear location', 'Ort entfernen', 'Quitar ubicación', 'Effacer le lieu', '場所をクリア', '清除地点'),
    ('Clear location “%1”', 'Ort „%1“ entfernen', 'Quitar ubicación «%1»', 'Effacer le lieu « %1 »', '場所「%1」をクリア', '清除地点“%1”'),
    ('Column axis', 'Spaltenachse', 'Eje de columnas', 'Axe des colonnes', '列の軸', '列轴'),
    ('Create label \\u201c%1\\u201d', 'Label „%1“ anlegen', 'Crear etiqueta «%1»', 'Créer l’étiquette « %1 »', 'ラベル「%1」を作成', '创建标签“%1”'),
    ('Day section (morning / afternoon / …)', 'Tagesabschnitt (Morgen / Nachmittag / …)', 'Parte del día (mañana / tarde / …)', 'Moment de la journée (matin / après-midi / …)', '時間帯 (朝 / 午後 / …)', '时段（上午 / 下午 / …）'),
    ('Days side by side', 'Tage nebeneinander', 'Días lado a lado', 'Jours côte à côte', '日を横に並べる', '日期并排'),
    ('Days stacked', 'Tage untereinander', 'Días apilados', 'Jours empilés', '日を縦に並べる', '日期堆叠'),
    ('Delete location', 'Ort löschen', 'Eliminar ubicación', 'Supprimer le lieu', '場所を削除', '删除地点'),
    ('Drop here', 'Hier ablegen', 'Soltar aquí', 'Déposer ici', 'ここにドロップ', '拖放到此处'),
    ('Due date:', 'Fälligkeit:', 'Vencimiento:', 'Échéance :', '期限:', '截止日期：'),
    ('Few', 'Wenige', 'Pocas', 'Peu', '少', '少'),
    ('Filter by KURRENT/LIST day section. Used by the Today view to group tasks into Morning, Afternoon, and Evening buckets.',
     'Nach Tagesabschnitt (KURRENT/LIST) filtern. Die Heute-Ansicht gruppiert damit Aufgaben in Morgen, Nachmittag und Abend.',
     'Filtrar por parte del día (KURRENT/LIST). La vista Hoy la usa para agrupar tareas en mañana, tarde y noche.',
     'Filtrer par moment de la journée (KURRENT/LIST). La vue Aujourd’hui s’en sert pour grouper les tâches en matin, après-midi et soir.',
     '時間帯 (KURRENT/LIST) で絞り込みます。今日ビューで朝・午後・夜に分けるのに使います。',
     '按时段（KURRENT/LIST）筛选。“今天”视图用它把任务分为上午、下午和晚上。'),
    ('Filter by a custom KURRENT/COLUMN value. Only needed when using Kanban with \\"Custom column\\" as source. Leave empty to ignore.',
     'Nach eigenem KURRENT/COLUMN-Wert filtern. Nur nötig, wenn Kanban „Eigene Spalte“ als Quelle nutzt. Leer lassen, um zu ignorieren.',
     'Filtrar por un valor propio de KURRENT/COLUMN. Solo hace falta si el Kanban usa «Columna propia» como origen. Déjalo vacío para ignorarlo.',
     'Filtrer par une valeur KURRENT/COLUMN personnalisée. Utile seulement si le Kanban utilise « Colonne personnalisée » comme source. Laisser vide pour ignorer.',
     '独自の KURRENT/COLUMN 値で絞り込みます。カンバンのソースが「カスタム列」の場合のみ必要です。空欄で無視します。',
     '按自定义 KURRENT/COLUMN 值筛选。仅当看板以“自定义列”为来源时需要。留空则忽略。'),
    ('Filter by priority level. \\"Any priority\\" shows all tasks.', 'Nach Priorität filtern. „Beliebige Priorität“ zeigt alle Aufgaben.', 'Filtrar por prioridad. «Cualquier prioridad» muestra todas las tareas.', 'Filtrer par priorité. « Toute priorité » affiche toutes les tâches.', '優先度で絞り込みます。「すべての優先度」ですべて表示します。', '按优先级筛选。“任意优先级”显示所有任务。'),
    ('Filter by task status. \\"Any status\\" shows tasks regardless of status.', 'Nach Status filtern. „Beliebiger Status“ zeigt Aufgaben unabhängig vom Status.', 'Filtrar por estado. «Cualquier estado» muestra las tareas sin importar su estado.', 'Filtrer par statut. « Tout statut » affiche les tâches quel que soit leur statut.', '状態で絞り込みます。「すべての状態」で状態に関係なく表示します。', '按状态筛选。“任意状态”显示所有状态的任务。'),
    ('Filter tasks by when they are due. \\"Any due date\\" shows all regardless of due date.', 'Nach Fälligkeit filtern. „Beliebige Fälligkeit“ zeigt alle unabhängig vom Datum.', 'Filtrar por vencimiento. «Cualquier vencimiento» muestra todas sin importar la fecha.', 'Filtrer par échéance. « Toute échéance » affiche tout, quelle que soit la date.', '期限で絞り込みます。「すべての期限」で期限に関係なく表示します。', '按截止时间筛选。“任意截止日期”显示所有任务。'),
    ('Filter tasks whose title or description contains this text. Leave empty to show all.', 'Aufgaben filtern, deren Titel oder Beschreibung diesen Text enthält. Leer lassen, um alle zu zeigen.', 'Filtrar tareas cuyo título o descripción contenga este texto. Déjalo vacío para mostrar todas.', 'Filtrer les tâches dont le titre ou la description contient ce texte. Laisser vide pour tout afficher.', 'タイトルか説明にこの文字列を含むタスクに絞り込みます。空欄ですべて表示します。', '筛选标题或描述包含此文本的任务。留空显示全部。'),
    ('Fr', 'Fr', 'vi', 've', '金', '五'),
    ('Group tasks', 'Aufgaben gruppieren', 'Agrupar tareas', 'Grouper les tâches', 'タスクをグループ化', '任务分组'),
    ('Group: %1', 'Gruppe: %1', 'Grupo: %1', 'Groupe : %1', 'グループ: %1', '分组：%1'),
    ('Has no location', 'Ohne Ort', 'Sin ubicación', 'Sans lieu', '場所なし', '无地点'),
    ('Has reminder', 'Mit Erinnerung', 'Con recordatorio', 'Avec rappel', 'リマインダーあり', '有提醒'),
    ('How tasks are ordered in this view. Leave at Default to use Priority → Due → Title.', 'Reihenfolge der Aufgaben in dieser Ansicht. „Standard“ sortiert nach Priorität → Fälligkeit → Titel.', 'Orden de las tareas en esta vista. «Predeterminado» usa Prioridad → Vencimiento → Título.', 'Ordre des tâches dans cette vue. « Par défaut » trie par Priorité → Échéance → Titre.', 'このビューでの並び順です。「既定」では優先度 → 期限 → タイトルの順です。', '此视图中任务的排序方式。“默认”按 优先级 → 截止 → 标题 排序。'),
    ('Icon displayed next to the Smart View in the sidebar.', 'Symbol neben der Smart View in der Seitenleiste.', 'Icono junto a la vista inteligente en la barra lateral.', 'Icône affichée à côté de la vue intelligente dans la barre latérale.', 'サイドバーでスマートビューの横に表示するアイコン。', '侧边栏中智能视图旁显示的图标。'),
    ('Include weekend', 'Wochenende einbeziehen', 'Incluir fin de semana', 'Inclure le week-end', '週末を含める', '包含周末'),
    ('Info journal', 'Info-Journal', 'Registro informativo', 'Journal info', '情報ジャーナル', '信息日志'),
    ('Journal diagnostics', 'Journal-Diagnose', 'Diagnóstico del registro', 'Diagnostic du journal', 'ジャーナル診断', '日志诊断'),
    ('Kanban columns', 'Kanban-Spalten', 'Columnas Kanban', 'Colonnes Kanban', 'カンバンの列', '看板列'),
    ('Kanban columns: %1', 'Kanban-Spalten: %1', 'Columnas Kanban: %1', 'Colonnes Kanban : %1', 'カンバンの列: %1', '看板列：%1'),
    ('Label (Z–A)', 'Label (Z–A)', 'Etiqueta (Z–A)', 'Étiquette (Z–A)', 'ラベル (Z–A)', '标签 (Z–A)'),
    ('Labels are already Kanban columns.', 'Labels sind bereits Kanban-Spalten.', 'Las etiquetas ya son columnas Kanban.', 'Les étiquettes sont déjà des colonnes Kanban.', 'ラベルはすでにカンバンの列です。', '标签已作为看板列。'),
    ('Labels are already swimlane rows.', 'Labels sind bereits Swimlane-Zeilen.', 'Las etiquetas ya son filas de carriles.', 'Les étiquettes sont déjà des lignes de couloirs.', 'ラベルはすでにスイムレーンの行です。', '标签已作为泳道行。'),
    ('Location (Z–A)', 'Ort (Z–A)', 'Ubicación (Z–A)', 'Lieu (Z–A)', '場所 (Z–A)', '地点 (Z–A)'),
    ('Locations', 'Orte', 'Ubicaciones', 'Lieux', '場所', '地点'),
    ('Locations come from the VTODO LOCATION field. Hidden locations will not appear in the sidebar filter list but remain on tasks.', 'Orte stammen aus dem VTODO-Feld LOCATION. Ausgeblendete Orte erscheinen nicht in der Filterliste der Seitenleiste, bleiben aber an den Aufgaben.', 'Las ubicaciones vienen del campo LOCATION de VTODO. Las ocultas no aparecen en el filtro de la barra lateral, pero siguen en las tareas.', 'Les lieux viennent du champ LOCATION de VTODO. Les lieux masqués n’apparaissent pas dans le filtre de la barre latérale mais restent sur les tâches.', '場所は VTODO の LOCATION フィールドから取得します。非表示の場所はサイドバーのフィルターに出ませんが、タスクには残ります。', '地点来自 VTODO 的 LOCATION 字段。隐藏的地点不会出现在侧边栏筛选中，但仍保留在任务上。'),
    ('Log Akonadi writes and sync state to the system journal', 'Akonadi-Schreibvorgänge und Sync-Status ins Systemjournal schreiben', 'Registrar escrituras de Akonadi y estado de sincronización en el diario del sistema', 'Journaliser les écritures Akonadi et l’état de synchro dans le journal système', 'Akonadi の書き込みと同期状態をシステムジャーナルに記録', '将 Akonadi 写入和同步状态记录到系统日志'),
    ('Log fetch, monitor, and collection details to the system journal', 'Abruf-, Monitor- und Sammlungsdetails ins Systemjournal schreiben', 'Registrar detalles de obtención, monitor y colecciones en el diario del sistema', 'Journaliser les détails de récupération, de suivi et de collections dans le journal système', '取得・監視・コレクションの詳細をシステムジャーナルに記録', '将获取、监视和集合详情记录到系统日志'),
    ('Logging', 'Protokollierung', 'Registro', 'Journalisation', 'ログ', '日志'),
    ('Maintenance', 'Wartung', 'Mantenimiento', 'Maintenance', 'メンテナンス', '维护'),
    ('Many', 'Viele', 'Muchas', 'Beaucoup', '多', '多'),
    ('Mo', 'Mo', 'lu', 'lu', '月', '一'),
    ('New location', 'Neuer Ort', 'Nueva ubicación', 'Nouveau lieu', '新しい場所', '新地点'),
    ('Next', 'Weiter', 'Siguiente', 'Suivant', '次へ', '下一个'),
    ('No events or tasks.', 'Keine Termine oder Aufgaben.', 'Sin eventos ni tareas.', 'Aucun événement ni tâche.', '予定もタスクもありません。', '没有事件或任务。'),
    ('No locations found. Locations are discovered from task LOCATION values in Akonadi, or add one below.', 'Keine Orte gefunden. Orte werden aus den LOCATION-Werten der Aufgaben in Akonadi ermittelt, oder du legst unten einen an.', 'No se encontraron ubicaciones. Se detectan de los valores LOCATION de las tareas en Akonadi, o añade una abajo.', 'Aucun lieu trouvé. Les lieux sont détectés à partir des valeurs LOCATION des tâches dans Akonadi, ou ajoutez-en un ci-dessous.', '場所が見つかりません。Akonadi のタスクの LOCATION から検出されます。下で追加することもできます。', '未找到地点。地点从 Akonadi 中任务的 LOCATION 值获取，也可在下方添加。'),
    ('No matching locations', 'Keine passenden Orte', 'Ninguna ubicación coincide', 'Aucun lieu correspondant', '一致する場所はありません', '没有匹配的地点'),
    ('No status', 'Kein Status', 'Sin estado', 'Aucun statut', '状態なし', '无状态'),
    ('Not available in the current view.', 'In der aktuellen Ansicht nicht verfügbar.', 'No disponible en la vista actual.', 'Indisponible dans la vue actuelle.', '現在のビューでは使用できません。', '当前视图中不可用。'),
    ('Only tasks matching ALL active rules are shown. Leave a filter on \\"Any\\" to disable it.', 'Es werden nur Aufgaben gezeigt, die ALLE aktiven Regeln erfüllen. Ein Filter auf „Beliebig“ ist ausgeschaltet.', 'Solo se muestran las tareas que cumplen TODAS las reglas activas. Deja un filtro en «Cualquiera» para desactivarlo.', 'Seules les tâches qui respectent TOUTES les règles actives sont affichées. Laissez un filtre sur « Tout » pour le désactiver.', '有効なすべてのルールに一致するタスクのみ表示します。「すべて」のままのフィルターは無効です。', '仅显示符合所有已启用规则的任务。筛选保持“任意”即为停用。'),
    ('Previous', 'Zurück', 'Anterior', 'Précédent', '前へ', '上一个'),
    ('Priorities are already Kanban columns.', 'Prioritäten sind bereits Kanban-Spalten.', 'Las prioridades ya son columnas Kanban.', 'Les priorités sont déjà des colonnes Kanban.', '優先度はすでにカンバンの列です。', '优先级已作为看板列。'),
    ('Priorities are already swimlane rows.', 'Prioritäten sind bereits Swimlane-Zeilen.', 'Las prioridades ya son filas de carriles.', 'Les priorités sont déjà des lignes de couloirs.', '優先度はすでにスイムレーンの行です。', '优先级已作为泳道行。'),
    ('Priority %1 (%2)', 'Priorität %1 (%2)', 'Prioridad %1 (%2)', 'Priorité %1 (%2)', '優先度 %1 (%2)', '优先级 %1（%2）'),
    ('Progress %1%', 'Fortschritt %1 %', 'Progreso %1 %', 'Progression %1 %', '進捗 %1%', '进度 %1%'),
    ('Progress is already used for Kanban columns.', 'Der Fortschritt dient bereits als Kanban-Spalten.', 'El progreso ya se usa para las columnas Kanban.', 'La progression sert déjà de colonnes Kanban.', '進捗はすでにカンバンの列に使われています。', '进度已用作看板列。'),
    ('Project (Z–A)', 'Projekt (Z–A)', 'Proyecto (Z–A)', 'Projet (Z–A)', 'プロジェクト (Z–A)', '项目 (Z–A)'),
    ('Projects are already Kanban columns.', 'Projekte sind bereits Kanban-Spalten.', 'Los proyectos ya son columnas Kanban.', 'Les projets sont déjà des colonnes Kanban.', 'プロジェクトはすでにカンバンの列です。', '项目已作为看板列。'),
    ('Projects are already plan rows.', 'Projekte sind bereits Plan-Zeilen.', 'Los proyectos ya son filas del plan.', 'Les projets sont déjà des lignes du plan.', 'プロジェクトはすでに計画の行です。', '项目已作为计划行。'),
    ('Projects are already swimlane rows.', 'Projekte sind bereits Swimlane-Zeilen.', 'Los proyectos ya son filas de carriles.', 'Les projets sont déjà des lignes de couloirs.', 'プロジェクトはすでにスイムレーンの行です。', '项目已作为泳道行。'),
    ('Remove label “%1”', 'Label „%1“ entfernen', 'Quitar etiqueta «%1»', 'Retirer l’étiquette « %1 »', 'ラベル「%1」を外す', '移除标签“%1”'),
    ('Remove label “%1” from this task?', 'Label „%1“ von dieser Aufgabe entfernen?', '¿Quitar la etiqueta «%1» de esta tarea?', 'Retirer l’étiquette « %1 » de cette tâche ?', 'このタスクからラベル「%1」を外しますか?', '从此任务移除标签“%1”？'),
    ('Remove label?', 'Label entfernen?', '¿Quitar etiqueta?', 'Retirer l’étiquette ?', 'ラベルを外しますか?', '移除标签？'),
    ('Repeat', 'Wiederholung', 'Repetir', 'Répétition', '繰り返し', '重复'),
    ('Sa', 'Sa', 'sá', 'sa', '土', '六'),
    ('Search or create label\\u2026', 'Label suchen oder anlegen…', 'Buscar o crear etiqueta…', 'Rechercher ou créer une étiquette…', 'ラベルを検索または作成…', '搜索或创建标签…'),
    ('Search or set location…', 'Ort suchen oder setzen…', 'Buscar o fijar ubicación…', 'Rechercher ou définir un lieu…', '場所を検索または設定…', '搜索或设置地点…'),
    ('Secrecy (reverse)', 'Vertraulichkeit (absteigend)', 'Confidencialidad (inversa)', 'Confidentialité (inverse)', '機密性 (逆順)', '保密性（倒序）'),
    ('Secrecy is already used for Kanban columns.', 'Die Vertraulichkeit dient bereits als Kanban-Spalten.', 'La confidencialidad ya se usa para las columnas Kanban.', 'La confidentialité sert déjà de colonnes Kanban.', '機密性はすでにカンバンの列に使われています。', '保密性已用作看板列。'),
    ('Section', 'Abschnitt', 'Sección', 'Section', 'セクション', '分区'),
    ('Set location “%1”', 'Ort „%1“ setzen', 'Fijar ubicación «%1»', 'Définir le lieu « %1 »', '場所「%1」を設定', '设置地点“%1”'),
    ('Set progress to %1', 'Fortschritt auf %1 setzen', 'Fijar progreso en %1', 'Régler la progression sur %1', '進捗を %1 に設定', '将进度设为 %1'),
    ('Set secrecy “%1”', 'Vertraulichkeit „%1“ setzen', 'Fijar confidencialidad «%1»', 'Définir la confidentialité « %1 »', '機密性「%1」を設定', '设置保密性“%1”'),
    ('Set status “%1”', 'Status „%1“ setzen', 'Fijar estado «%1»', 'Définir le statut « %1 »', '状態「%1」を設定', '设置状态“%1”'),
    ('Show only tasks from a specific project (Akonadi collection). \\"Any project\\" disables this filter.', 'Nur Aufgaben aus einem bestimmten Projekt (Akonadi-Sammlung) zeigen. „Beliebiges Projekt“ schaltet den Filter aus.', 'Mostrar solo tareas de un proyecto (colección de Akonadi). «Cualquier proyecto» desactiva este filtro.', 'N’afficher que les tâches d’un projet (collection Akonadi). « Tout projet » désactive ce filtre.', '特定のプロジェクト (Akonadi コレクション) のタスクのみ表示します。「すべてのプロジェクト」で無効になります。', '仅显示特定项目（Akonadi 集合）的任务。“任意项目”停用此筛选。'),
    ('Show only tasks with a specific label (Akonadi category). \\"Any label\\" disables this filter.', 'Nur Aufgaben mit einem bestimmten Label (Akonadi-Kategorie) zeigen. „Beliebiges Label“ schaltet den Filter aus.', 'Mostrar solo tareas con una etiqueta (categoría de Akonadi). «Cualquier etiqueta» desactiva este filtro.', 'N’afficher que les tâches portant une étiquette (catégorie Akonadi). « Toute étiquette » désactive ce filtre.', '特定のラベル (Akonadi カテゴリ) を持つタスクのみ表示します。「すべてのラベル」で無効になります。', '仅显示带有特定标签（Akonadi 类别）的任务。“任意标签”停用此筛选。'),
    ('Show this location in the sidebar filter', 'Diesen Ort im Filter der Seitenleiste zeigen', 'Mostrar esta ubicación en el filtro de la barra lateral', 'Afficher ce lieu dans le filtre de la barre latérale', 'この場所をサイドバーのフィルターに表示', '在侧边栏筛选中显示此地点'),
    ('Smart View name', 'Name der Smart View', 'Nombre de la vista inteligente', 'Nom de la vue intelligente', 'スマートビューの名前', '智能视图名称'),
    ('Star', 'Stern', 'Estrella', 'Étoile', '星', '星形'),
    ('Start', 'Beginn', 'Inicio', 'Début', '開始', '开始'),
    ('Status (reverse)', 'Status (absteigend)', 'Estado (inverso)', 'Statut (inverse)', '状態 (逆順)', '状态（倒序）'),
    ('Status is already used for Kanban columns.', 'Der Status dient bereits als Kanban-Spalten.', 'El estado ya se usa para las columnas Kanban.', 'Le statut sert déjà de colonnes Kanban.', '状態はすでにカンバンの列に使われています。', '状态已用作看板列。'),
    ('Stores KURRENT/LIST for Today-view day sections (Morning, Afternoon, Evening). Also used as the Kanban “Day section” column source.', 'Speichert KURRENT/LIST für die Tagesabschnitte der Heute-Ansicht (Morgen, Nachmittag, Abend). Dient auch als Quelle der Kanban-Spalten „Tagesabschnitt“.', 'Guarda KURRENT/LIST para las partes del día de la vista Hoy (mañana, tarde, noche). También es el origen de las columnas Kanban «Parte del día».', 'Enregistre KURRENT/LIST pour les moments de la vue Aujourd’hui (matin, après-midi, soir). Sert aussi de source aux colonnes Kanban « Moment de la journée ».', '今日ビューの時間帯 (朝・午後・夜) 用に KURRENT/LIST を保存します。カンバンの「時間帯」列のソースにもなります。', '为“今天”视图的时段（上午、下午、晚上）保存 KURRENT/LIST，也作为看板“时段”列的来源。'),
    ('Su', 'So', 'do', 'di', '日', '日'),
    ('Th', 'Do', 'ju', 'je', '木', '四'),
    ('The display name shown in the sidebar.', 'Der Name in der Seitenleiste.', 'El nombre que aparece en la barra lateral.', 'Le nom affiché dans la barre latérale.', 'サイドバーに表示する名前。', '侧边栏中显示的名称。'),
    ('The main-pane view mode used when this Smart View is active.', 'Die Darstellung des Hauptbereichs, solange diese Smart View aktiv ist.', 'El modo de vista del panel principal mientras esta vista inteligente está activa.', 'Le mode d’affichage du panneau principal quand cette vue intelligente est active.', 'このスマートビューが有効なときのメイン領域の表示モード。', '此智能视图激活时主区域使用的视图模式。'),
    ('Tu', 'Di', 'ma', 'ma', '火', '二'),
    ('Unlabeled view does not apply when Kanban uses labels as columns.', 'Die Ansicht „Ohne Label“ greift nicht, wenn Kanban Labels als Spalten nutzt.', 'La vista «Sin etiqueta» no se aplica si el Kanban usa etiquetas como columnas.', 'La vue « Sans étiquette » ne s’applique pas si le Kanban utilise les étiquettes comme colonnes.', 'カンバンがラベルを列にしている場合、「ラベルなし」ビューは適用されません。', '看板以标签为列时，“无标签”视图不适用。'),
    ('Use “%1”', '„%1“ verwenden', 'Usar «%1»', 'Utiliser « %1 »', '「%1」を使用', '使用“%1”'),
    ('Verbose journal', 'Ausführliches Journal', 'Registro detallado', 'Journal détaillé', '詳細ジャーナル', '详细日志'),
    ('View:', 'Ansicht:', 'Vista:', 'Vue :', '表示:', '视图：'),
    ('We', 'Mi', 'mi', 'me', '水', '三'),
    ('When checked, only recurring tasks are shown.', 'Wenn aktiv, werden nur wiederkehrende Aufgaben gezeigt.', 'Si está marcado, solo se muestran las tareas periódicas.', 'Si coché, seules les tâches récurrentes sont affichées.', 'オンにすると繰り返しタスクのみ表示します。', '勾选后仅显示重复任务。'),
    ('Year', 'Jahr', 'Año', 'Année', '年', '年'),
    ('task completed', 'Aufgabe erledigt', 'tarea completada', 'tâche terminée', '件完了', '个任务已完成'),
    ('task due', 'Aufgabe fällig', 'tarea con vencimiento', 'tâche à échéance', '件期限', '个任务到期'),
    ('tasks completed', 'Aufgaben erledigt', 'tareas completadas', 'tâches terminées', '件完了', '个任务已完成'),
    ('tasks due', 'Aufgaben fällig', 'tareas con vencimiento', 'tâches à échéance', '件期限', '个任务到期'),
    # Already translated in German only.
    ('Planning horizon', 'Planungshorizont', 'Horizonte de planificación', 'Horizon de planification', '計画期間', '计划范围'),
    ('Row axis', 'Zeilenachse', 'Eje de filas', 'Axe des lignes', '行の軸', '行轴'),
    ('Show undated tasks', 'Undatierte Aufgaben anzeigen', 'Mostrar tareas sin fecha', 'Afficher les tâches sans date', '日付なしのタスクを表示', '显示无日期任务'),
    ('Time grouping', 'Zeiteinteilung', 'Agrupación temporal', 'Regroupement temporel', '時間のまとまり', '时间分组'),
    ('Any label', None, 'Cualquier etiqueta', 'Toute étiquette', 'すべてのラベル', '任意标签'),
    ('Any project', None, 'Cualquier proyecto', 'Tout projet', 'すべてのプロジェクト', '任意项目'),
    ('Any section', None, 'Cualquier sección', 'Toute section', 'すべてのセクション', '任意分区'),
    ('Briefcase', None, 'Maletín', 'Mallette', 'ブリーフケース', '公文包'),
    ('Calendar', None, 'Calendario', 'Agenda', 'カレンダー', '日历'),
    ('Checkmark', None, 'Marca de verificación', 'Coche', 'チェックマーク', '勾号'),
    ('Clock', None, 'Reloj', 'Horloge', '時計', '时钟'),
    ('Contains…', None, 'Contiene…', 'Contient…', '含む…', '包含…'),
    ('Custom (manual)', None, 'Personalizado (manual)', 'Personnalisé (manuel)', 'カスタム (手動)', '自定义（手动）'),
    ('Custom column:', None, 'Columna propia:', 'Colonne personnalisée :', 'カスタム列:', '自定义列：'),
    ('Day section:', None, 'Parte del día:', 'Moment de la journée :', '時間帯:', '时段：'),
    ('Default (Priority → Due → Title)', None, 'Predeterminado (Prioridad → Vencimiento → Título)', 'Par défaut (Priorité → Échéance → Titre)', '既定 (優先度 → 期限 → タイトル)', '默认（优先级 → 截止 → 标题）'),
    ('Filter', None, 'Filtro', 'Filtre', 'フィルター', '筛选'),
    ('Filter Rules', None, 'Reglas de filtro', 'Règles de filtre', 'フィルタールール', '筛选规则'),
    ('Flag', None, 'Bandera', 'Drapeau', '旗', '旗帜'),
    ('Folder', None, 'Carpeta', 'Dossier', 'フォルダー', '文件夹'),
    ('Heart', None, 'Corazón', 'Cœur', 'ハート', '心形'),
    ('Home', None, 'Casa', 'Maison', '家', '家'),
    ('Icon:', None, 'Icono:', 'Icône :', 'アイコン:', '图标：'),
    ('KURRENT/COLUMN value…', None, 'Valor de KURRENT/COLUMN…', 'Valeur KURRENT/COLUMN…', 'KURRENT/COLUMN の値…', 'KURRENT/COLUMN 值…'),
    ('Label:', None, 'Etiqueta:', 'Étiquette :', 'ラベル:', '标签：'),
    ('Lightbulb', None, 'Bombilla', 'Ampoule', '電球', '灯泡'),
    ('Name:', None, 'Nombre:', 'Nom :', '名前:', '名称：'),
    ('Recurring tasks only', None, 'Solo tareas periódicas', 'Tâches récurrentes uniquement', '繰り返しタスクのみ', '仅重复任务'),
    ('Search text:', None, 'Texto de búsqueda:', 'Texte recherché :', '検索文字列:', '搜索文本：'),
    ('Sort by:', None, 'Ordenar por:', 'Trier par :', '並べ替え:', '排序方式：'),
    ('Tag', None, 'Etiqueta', 'Étiquette', 'タグ', '标签'),
    ('View mode:', None, 'Modo de vista:', 'Mode d’affichage :', '表示モード:', '视图模式：'),
    ('Warning', None, 'Advertencia', 'Avertissement', '警告', '警告'),
    ('Work', None, 'Trabajo', 'Travail', '仕事', '工作'),
    # Backend column labels (tasklogic kanbanColumnLabel), translated in KanbanView.
    ('Cancelled', 'Abgebrochen', 'Cancelada', 'Annulée', 'キャンセル', '已取消'),
    ('Open', 'Offen', 'Abierta', 'Ouverte', '未完了', '未完成'),
    ('Done', 'Erledigt', 'Hecha', 'Faite', '完了', '已完成'),
    ('This week', 'Diese Woche', 'Esta semana', 'Cette semaine', '今週', '本周'),
    ('Unscheduled', 'Ungeplant', 'Sin planificar', 'Non planifiée', '未計画', '未安排'),
    # Review: heatmap day list, calendar tiles and empty day.
    ('Add task for this day', 'Aufgabe für diesen Tag anlegen', 'Añadir tarea para este día', 'Ajouter une tâche pour ce jour', 'この日にタスクを追加', '为这一天添加任务'),
    ('Completed on %1', 'Erledigt am %1', 'Completadas el %1', 'Terminées le %1', '%1 に完了', '%1 完成'),
    ('Due on %1', 'Fällig am %1', 'Vencen el %1', 'À échéance le %1', '%1 が期限', '%1 到期'),
    ('Events', 'Termine', 'Eventos', 'Événements', '予定', '事件'),
    ('Events this week', 'Termine diese Woche', 'Eventos esta semana', 'Événements cette semaine', '今週の予定', '本周事件'),
    ('Next event', 'Nächster Termin', 'Próximo evento', 'Prochain événement', '次の予定', '下一个事件'),
    ('Next event · %1', 'Nächster Termin · %1', 'Próximo evento · %1', 'Prochain événement · %1', '次の予定 · %1', '下一个事件 · %1'),
    ('Nothing on this day.', 'An diesem Tag nichts.', 'Nada este día.', 'Rien ce jour-là.', 'この日は何もありません。', '这一天没有内容。'),
    ('Open in calendar', 'Im Kalender öffnen', 'Abrir en el calendario', 'Ouvrir dans l’agenda', 'カレンダーで開く', '在日历中打开'),
    ('Tasks due', 'Fällige Aufgaben', 'Tareas pendientes', 'Tâches à échéance', '期限のタスク', '到期任务'),
    ('Tasks this week', 'Aufgaben diese Woche', 'Tareas esta semana', 'Tâches cette semaine', '今週のタスク', '本周任务'),
    # Review: inspector, editor, Kanban setting.
    ('Date', 'Datum', 'Fecha', 'Date', '日付', '日期'),
    ('Edit here', 'Hier bearbeiten', 'Editar aquí', 'Modifier ici', 'ここで編集', '在此编辑'),
    ('Hide the Canceled column', 'Spalte „Abgebrochen“ ausblenden', 'Ocultar la columna Cancelada', 'Masquer la colonne Annulée', '「キャンセル」列を隠す', '隐藏“已取消”列'),
    ('New task', 'Neue Aufgabe', 'Nueva tarea', 'Nouvelle tâche', '新しいタスク', '新任务'),
    ('Time', 'Uhrzeit', 'Hora', 'Heure', '時刻', '时间'),
    ('today', 'heute', 'hoy', 'aujourd’hui', '今日', '今天'),
    ('tomorrow', 'morgen', 'mañana', 'demain', '明日', '明天'),
    ('yesterday', 'gestern', 'ayer', 'hier', '昨日', '昨天'),
    # Settings review (eight pages).
    ('%1 px', '%1 px', '%1 px', '%1 px', '%1 px', '%1 像素'),
    ('Add CalDAV or Nextcloud calendars in %1 (DAV groupware resource).', 'CalDAV- oder Nextcloud-Kalender fügst du in %1 hinzu (DAV-Groupware-Ressource).', 'Añade calendarios CalDAV o Nextcloud en %1 (recurso DAV groupware).', 'Ajoutez des agendas CalDAV ou Nextcloud dans %1 (ressource DAV groupware).', 'CalDAV や Nextcloud のカレンダーは %1 で追加します (DAV グループウェアリソース)。', '在 %1 中添加 CalDAV 或 Nextcloud 日历（DAV 群件资源）。'),
    ('Add CalDAV or Nextcloud calendars in KOrganizer or Merkuro (DAV groupware resource).', 'CalDAV- oder Nextcloud-Kalender fügst du in KOrganizer oder Merkuro hinzu (DAV-Groupware-Ressource).', 'Añade calendarios CalDAV o Nextcloud en KOrganizer o Merkuro (recurso DAV groupware).', 'Ajoutez des agendas CalDAV ou Nextcloud dans KOrganizer ou Merkuro (ressource DAV groupware).', 'CalDAV や Nextcloud のカレンダーは KOrganizer か Merkuro で追加します (DAV グループウェアリソース)。', '在 KOrganizer 或 Merkuro 中添加 CalDAV 或 Nextcloud 日历（DAV 群件资源）。'),
    ('Advanced', 'Erweitert', 'Avanzado', 'Avancé', '詳細', '高级'),
    ('Also complete subtasks', 'Unteraufgaben mit abhaken', 'Completar también las subtareas', 'Terminer aussi les sous-tâches', 'サブタスクも完了にする', '同时完成子任务'),
    ('Automatic colour', 'Automatische Farbe', 'Color automático', 'Couleur automatique', '自動の色', '自动颜色'),
    ('Behaviour', 'Verhalten', 'Comportamiento', 'Comportement', '動作', '行为'),
    ('Call the plumber', 'Klempner anrufen', 'Llamar al fontanero', 'Appeler le plombier', '配管工に電話', '给水管工打电话'),
    ('Choose colour…', 'Farbe wählen …', 'Elegir color…', 'Choisir une couleur…', '色を選択…', '选择颜色…'),
    ('Colour %1', 'Farbe %1', 'Color %1', 'Couleur %1', '色 %1', '颜色 %1'),
    ('Connected', 'Verbunden', 'Conectado', 'Connecté', '接続済み', '已连接'),
    ('Connecting…', 'Verbinde …', 'Conectando…', 'Connexion…', '接続中…', '正在连接…'),
    ('Copied', 'Kopiert', 'Copiado', 'Copié', 'コピーしました', '已复制'),
    ('Day sections', 'Tagesabschnitte', 'Partes del día', 'Moments de la journée', '時間帯', '时段'),
    ('Default project for new tasks', 'Standardprojekt für neue Aufgaben', 'Proyecto predeterminado para tareas nuevas', 'Projet par défaut des nouvelles tâches', '新しいタスクの既定のプロジェクト', '新任务的默认项目'),
    ('Delete “%1”?', '„%1“ löschen?', '¿Eliminar «%1»?', 'Supprimer « %1 » ?', '「%1」を削除しますか?', '删除“%1”？'),
    ('Delete…', 'Löschen …', 'Eliminar…', 'Supprimer…', '削除…', '删除…'),
    ('Drag to reorder, switch to show or hide.', 'Ziehen zum Umsortieren, Schalter zum Ein- und Ausblenden.', 'Arrastra para reordenar; el interruptor muestra u oculta.', 'Glissez pour réordonner, l’interrupteur affiche ou masque.', 'ドラッグで並べ替え、スイッチで表示/非表示。', '拖动以排序，开关用于显示或隐藏。'),
    ('Errands', 'Besorgungen', 'Recados', 'Courses', '用事', '跑腿'),
    ('From', 'Von', 'De', 'De', '開始', '从'),
    ('In the wide layout with the inspector on, a click shows the task in the inspector. Double-click always opens the full editor.', 'Im breiten Layout mit Inspektor zeigt ein Klick die Aufgabe im Inspektor. Doppelklick öffnet immer den vollständigen Editor.', 'En el diseño ancho con el inspector activo, un clic muestra la tarea en el inspector. El doble clic siempre abre el editor completo.', 'En disposition large avec l’inspecteur, un clic affiche la tâche dans l’inspecteur. Le double-clic ouvre toujours l’éditeur complet.', 'ワイドレイアウトでインスペクターが有効なら、クリックでタスクをインスペクターに表示します。ダブルクリックは常にフルエディターを開きます。', '在宽布局中开启检查器时，单击会在检查器中显示任务。双击始终打开完整编辑器。'),
    ('Inspector beside the list', 'Inspektor neben der Liste', 'Inspector junto a la lista', 'Inspecteur à côté de la liste', 'リストの横にインスペクター', '列表旁的检查器'),
    ('Labels are task categories in Akonadi. Hidden labels stay on the tasks but are not listed in the sidebar.', 'Labels sind Aufgabenkategorien in Akonadi. Ausgeblendete Labels bleiben an den Aufgaben, erscheinen aber nicht in der Seitenleiste.', 'Las etiquetas son categorías de tareas en Akonadi. Las ocultas siguen en las tareas, pero no aparecen en la barra lateral.', 'Les étiquettes sont les catégories de tâches d’Akonadi. Masquées, elles restent sur les tâches mais ne sont pas listées dans la barre latérale.', 'ラベルは Akonadi のタスクカテゴリです。非表示のラベルはタスクに残りますが、サイドバーには出ません。', '标签是 Akonadi 中的任务类别。隐藏的标签仍保留在任务上，但不在侧边栏列出。'),
    ('Leaking tap in the kitchen, ask for Thursday morning.', 'Tropfender Wasserhahn in der Küche, nach Donnerstagvormittag fragen.', 'Grifo que gotea en la cocina, pedir el jueves por la mañana.', 'Robinet qui fuit dans la cuisine, demander jeudi matin.', '台所の蛇口の水漏れ、木曜の午前を頼む。', '厨房水龙头漏水，约周四上午。'),
    ('Load', 'Laden', 'Cargar', 'Charger', '読み込む', '加载'),
    ('Locations come from the task’s location field. Hidden locations stay on the tasks but are not listed in the sidebar.', 'Orte stammen aus dem Ortsfeld der Aufgabe. Ausgeblendete Orte bleiben an den Aufgaben, erscheinen aber nicht in der Seitenleiste.', 'Las ubicaciones vienen del campo de ubicación de la tarea. Las ocultas siguen en las tareas, pero no aparecen en la barra lateral.', 'Les lieux viennent du champ lieu de la tâche. Masqués, ils restent sur les tâches mais ne sont pas listés dans la barre latérale.', '場所はタスクの場所フィールドから取得します。非表示の場所はタスクに残りますが、サイドバーには出ません。', '地点来自任务的地点字段。隐藏的地点仍保留在任务上，但不在侧边栏列出。'),
    ('Managed under Views › Smart Views.', 'Verwaltet unter Ansichten › Smart Views.', 'Se gestionan en Vistas › Vistas inteligentes.', 'Gérées dans Vues › Vues intelligentes.', 'ビュー › スマートビューで管理します。', '在 视图 › 智能视图 中管理。'),
    ('More', 'Mehr', 'Más', 'Plus', 'その他', '更多'),
    ('Moving a card changes', 'Verschieben einer Karte ändert', 'Mover una tarjeta cambia', 'Déplacer une carte modifie', 'カードの移動で変更するもの', '移动卡片时更改'),
    ('Multi-select with Ctrl+click', 'Mehrfachauswahl mit Strg+Klick', 'Selección múltiple con Ctrl+clic', 'Sélection multiple avec Ctrl+clic', 'Ctrl+クリックで複数選択', 'Ctrl+单击多选'),
    ('No Smart Views yet. Create one or copy a built-in view.', 'Noch keine Smart Views. Lege eine an oder kopiere eine eingebaute Ansicht.', 'Aún no hay vistas inteligentes. Crea una o copia una vista integrada.', 'Aucune vue intelligente pour l’instant. Créez-en une ou copiez une vue intégrée.', 'スマートビューはまだありません。作成するか組み込みビューをコピーしてください。', '还没有智能视图。新建一个或复制内置视图。'),
    ('No reminders during busy events', 'Keine Erinnerungen während belegter Termine', 'Sin recordatorios durante eventos ocupados', 'Pas de rappels pendant les événements occupés', '予定のある時間は通知しない', '忙碌事件期间不提醒'),
    ('No reminders during these hours', 'Keine Erinnerungen in diesen Stunden', 'Sin recordatorios en estas horas', 'Pas de rappels pendant ces heures', 'この時間帯は通知しない', '这些时段不提醒'),
    ('None yet. Create them under Views › Smart Views.', 'Noch keine. Lege sie unter Ansichten › Smart Views an.', 'Ninguna aún. Créalas en Vistas › Vistas inteligentes.', 'Aucune pour l’instant. Créez-les dans Vues › Vues intelligentes.', 'まだありません。ビュー › スマートビューで作成します。', '还没有。在 视图 › 智能视图 中创建。'),
    ('Notifications work.', 'Benachrichtigungen funktionieren.', 'Las notificaciones funcionan.', 'Les notifications fonctionnent.', '通知は正常に動作しています。', '通知正常。'),
    ('Off under “Load”: the calendar is not read at all. Off under “Sidebar”: its tasks load but the project is not listed.', 'Aus bei „Laden“: Der Kalender wird gar nicht gelesen. Aus bei „Seitenleiste“: Die Aufgaben werden geladen, das Projekt aber nicht aufgeführt.', 'Desactivado en «Cargar»: el calendario no se lee. Desactivado en «Barra lateral»: sus tareas se cargan, pero el proyecto no aparece.', 'Désactivé sous « Charger » : l’agenda n’est pas lu du tout. Désactivé sous « Barre latérale » : ses tâches sont chargées mais le projet n’est pas listé.', '「読み込む」がオフ: カレンダーを読みません。「サイドバー」がオフ: タスクは読み込みますが、プロジェクトは表示しません。', '“加载”关闭：完全不读取该日历。“侧边栏”关闭：任务会加载，但项目不列出。'),
    ('Only the custom column', 'Nur die eigene Spalte', 'Solo la columna propia', 'Seulement la colonne personnalisée', 'カスタム列のみ', '仅自定义列'),
    ('Only with Shift or Ctrl held', 'Nur mit gedrückter Umschalt- oder Strg-Taste', 'Solo manteniendo Mayús o Ctrl', 'Seulement avec Maj ou Ctrl enfoncé', 'Shift か Ctrl を押しているときのみ', '仅在按住 Shift 或 Ctrl 时'),
    ('Open %1', '%1 öffnen', 'Abrir %1', 'Ouvrir %1', '%1 を開く', '打开 %1'),
    ('Organize', 'Organisieren', 'Organizar', 'Organiser', '整理', '整理'),
    ('Panel & notifications', 'Panel & Hinweise', 'Panel y notificaciones', 'Panneau et notifications', 'パネルと通知', '面板与通知'),
    ('Preview', 'Vorschau', 'Vista previa', 'Aperçu', 'プレビュー', '预览'),
    ('Read this calendar when loading tasks', 'Diesen Kalender beim Laden der Aufgaben lesen', 'Leer este calendario al cargar tareas', 'Lire cet agenda au chargement des tâches', 'タスクの読み込み時にこのカレンダーを読む', '加载任务时读取此日历'),
    ('Select only', 'Nur auswählen', 'Solo seleccionar', 'Sélectionner seulement', '選択のみ', '仅选择'),
    ('Send test notification', 'Test-Benachrichtigung senden', 'Enviar notificación de prueba', 'Envoyer une notification de test', 'テスト通知を送る', '发送测试通知'),
    ('Sent.', 'Gesendet.', 'Enviada.', 'Envoyée.', '送信しました。', '已发送。'),
    ('Show overdue tasks (tile, chip or notice)', 'Überfällige anzeigen (Kachel, Chip oder Hinweis)', 'Mostrar vencidas (mosaico, chip o aviso)', 'Afficher les tâches en retard (tuile, puce ou avis)', '期限切れを表示 (タイル・チップ・通知)', '显示逾期任务（磁贴、标签或提示）'),
    ('Snoozing only moves the reminder, not the due date.', 'Schlummern verschiebt nur die Erinnerung, nicht die Fälligkeit.', 'Posponer solo mueve el recordatorio, no el vencimiento.', 'Répéter ne déplace que le rappel, pas l’échéance.', 'スヌーズで動くのはリマインダーだけで、期限は変わりません。', '稍后提醒只推迟提醒，不改截止日期。'),
    ('The field of the column (default)', 'Das Feld der Spalte (Standard)', 'El campo de la columna (predeterminado)', 'Le champ de la colonne (par défaut)', '列のフィールド (既定)', '该列对应的字段（默认）'),
    ('This build has no notification support.', 'Dieser Build unterstützt keine Benachrichtigungen.', 'Esta compilación no admite notificaciones.', 'Cette version ne prend pas en charge les notifications.', 'このビルドは通知に対応していません。', '此版本不支持通知。'),
    ('Tick off', 'Abhaken', 'Marcar', 'Cocher', 'チェック', '勾选'),
    ('Today groups its tasks into morning, afternoon and evening from these times.', 'Heute gruppiert seine Aufgaben ab diesen Uhrzeiten in Morgen, Nachmittag und Abend.', 'Hoy agrupa sus tareas en mañana, tarde y noche a partir de estas horas.', 'Aujourd’hui groupe ses tâches en matin, après-midi et soir à partir de ces heures.', '今日ビューはこの時刻でタスクを朝・午後・夜に分けます。', '“今天”按这些时间将任务分为上午、下午和晚上。'),
    ('Version', 'Version', 'Versión', 'Version', 'バージョン', '版本'),
    ('Widget %1 · Plugin %2', 'Widget %1 · Plugin %2', 'Widget %1 · Plugin %2', 'Widget %1 · Plugin %2', 'ウィジェット %1 · プラグイン %2', '小部件 %1 · 插件 %2'),
    ('Widget and plugin versions differ. Reinstall Kurrent so both match.', 'Widget- und Plugin-Version unterscheiden sich. Installiere Kurrent neu, damit beide passen.', 'Las versiones del widget y del plugin difieren. Reinstala Kurrent para que coincidan.', 'Les versions du widget et du plugin diffèrent. Réinstallez Kurrent pour les aligner.', 'ウィジェットとプラグインのバージョンが違います。Kurrent を再インストールしてください。', '小部件与插件版本不一致。请重新安装 Kurrent。'),
    ('With tiles the overdue tile offers “Move all to today”; the narrow layout shows a chip in the header; otherwise a notice above the tasks.', 'Mit Kacheln bietet die Überfällig-Kachel „Alle auf heute“; das schmale Layout zeigt einen Chip in der Kopfzeile; sonst erscheint ein Hinweis über den Aufgaben.', 'Con mosaicos, el de vencidas ofrece «Mover todo a hoy»; el diseño estrecho muestra un chip en la cabecera; si no, un aviso sobre las tareas.', 'Avec les tuiles, la tuile « En retard » propose « Tout à aujourd’hui » ; la disposition étroite affiche une puce dans l’en-tête ; sinon un avis au-dessus des tâches.', 'タイルがあれば期限切れタイルに「すべて今日へ」、狭いレイアウトではヘッダーにチップ、それ以外はタスクの上に通知を表示します。', '有磁贴时，逾期磁贴提供“全部移到今天”；窄布局在标题栏显示标签；否则在任务上方显示提示。'),
    ('You can also drag the edge of the sidebar.', 'Du kannst auch den Rand der Seitenleiste ziehen.', 'También puedes arrastrar el borde de la barra lateral.', 'Vous pouvez aussi faire glisser le bord de la barre latérale.', 'サイドバーの端をドラッグしても変えられます。', '也可以拖动侧边栏边缘。'),
    ('to', 'bis', 'a', 'à', 'から', '到'),
    ('Writes and sync state', 'Schreibvorgänge und Sync-Status', 'Escrituras y estado de sincronización', 'Écritures et état de synchro', '書き込みと同期状態', '写入与同步状态'),
    ('Fetch, monitor and collection details', 'Abruf-, Monitor- und Sammlungsdetails', 'Detalles de obtención, monitor y colecciones', 'Détails de récupération, de suivi et de collections', '取得・監視・コレクションの詳細', '获取、监视与集合详情'),
]

_LANGS = ["de", "es", "fr", "ja", "zh_CN"]
REVIEW = {lang: {} for lang in _LANGS}
for _row in _ROWS:
    for _i, _lang in enumerate(_LANGS):
        if _row[_i + 1] is not None:
            REVIEW[_lang][_row[0]] = _row[_i + 1]


# Consistent terms (x4): win over older catalog entries.
REVIEW_OVERRIDES = {
    'de': {
        'Priorities': 'Prioritäten',
        'Duplicate built-in view…': 'Eingebaute Ansicht kopieren …',
    },
}

# Relative due dates in the inspector, settings counts (i18np).
PLURAL_REVIEW = {
    '%1 calendar': {
        'msgid_plural': '%1 calendars',
        'de': ['%1 Kalender', '%1 Kalender'],
        'es': ['%1 calendario', '%1 calendarios'],
        'fr': ['%1 agenda', '%1 agendas'],
        'ja': ['%1 個のカレンダー'],
        'zh_CN': ['%1 个日历', '%1 个日历'],
    },
    'It is removed from %1 task.': {
        'msgid_plural': 'It is removed from %1 tasks.',
        'de': ['Es wird von %1 Aufgabe entfernt.', 'Es wird von %1 Aufgaben entfernt.'],
        'es': ['Se quitará de %1 tarea.', 'Se quitará de %1 tareas.'],
        'fr': ['Il sera retiré de %1 tâche.', 'Il sera retiré de %1 tâches.'],
        'ja': ['%1 件のタスクから外されます。'],
        'zh_CN': ['将从 %1 个任务中移除。', '将从 %1 个任务中移除。'],
    },
    'in %1 day': {
        'msgid_plural': 'in %1 days',
        'de': ['in %1 Tag', 'in %1 Tagen'],
        'es': ['en %1 día', 'en %1 días'],
        'fr': ['dans %1 jour', 'dans %1 jours'],
        'ja': ['%1 日後'],
        'zh_CN': ['%1 天后', '%1 天后'],
    },
    '%1 day ago': {
        'msgid_plural': '%1 days ago',
        'de': ['vor %1 Tag', 'vor %1 Tagen'],
        'es': ['hace %1 día', 'hace %1 días'],
        'fr': ['il y a %1 jour', 'il y a %1 jours'],
        'ja': ['%1 日前'],
        'zh_CN': ['%1 天前', '%1 天前'],
    },
}
